// Runtime-composed source module. Keep declarations in shared application scope.
// ── Vendor information ──
let vendorView='guide',vendorEditMode=false,activeVendorProjectId=null,vendorProjectEditMode=false,vendorProjectDraft=null,otherVendorFilter='all',otherVendorSearch='',materialGuides=[],activeMaterialGuideId='',guideEditing=false,guideSeedInFlight=false;
async function ensureMaterialGuideSeed(){if(localTestMode||guideSeedInFlight||materialGuides.length)return;guideSeedInFlight=true;try{const seed=await (await fetch(new URL('assets/material-guide-seed.json',window.__APP_BASE_URL__||location.href))).json();await Promise.all(seed.map(item=>addDoc(collection(db,'materialGuides'),{...item,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})));}catch(error){console.error('material guide seed failed',error);}finally{guideSeedInFlight=false;}}
function vendorCategoryName(id,list){return(list.find(x=>x.id===id)||{}).name||'未分類';}
function vendorSafeUrl(url){try{const u=new URL(url);return/^https?:$/.test(u.protocol)?u.href:'';}catch(e){return'';}}
function formatVendorPhone(value){const digits=String(value||'').replace(/\D/g,'').slice(0,10);return digits.length===10?digits.slice(0,4)+'-'+digits.slice(4):digits;}
window.formatVendorPhoneInput=function(input){input.value=formatVendorPhone(input.value);}
function renderVendors(){
  const el=$('panel-vendors');if(!el)return;
  const pendingSites=pendingTradeProjectsCount();
  const editAction=isAdmin()&&vendorView==='guide'?`<button class="btn btn-sm ${guideEditing?'btn-p':''}" onclick="toggleGuideEditing()">${guideEditing?'✓ 完成':'✎ 編輯'}</button>`:isAdmin()&&vendorView==='trade'?`<button class="btn btn-sm ${vendorEditMode?'btn-p':''}" onclick="toggleVendorEditMode()">${vendorEditMode?'✓ 完成':'✎ 編輯'}</button>`:'';
  el.innerHTML=`<div class="vendor-head"><div class="vendor-head-info"></div><div class="vendor-tabs"><button class="vendor-tab ${vendorView==='trade'?'on':''}" onclick="setVendorView('trade')">施工廠商名錄</button><button class="vendor-tab ${vendorView==='sites'?'on':''}" onclick="setVendorView('sites')">案件工班${pendingSites?` <span class="pend pend-r">${pendingSites}</span>`:''}</button><button class="vendor-tab ${vendorView==='other'?'on':''}" onclick="setVendorView('other')">廠商資料庫</button><button class="vendor-tab ${vendorView==='guide'?'on':''}" onclick="setVendorView('guide')">選材／選商指南</button></div>${editAction?`<div class="vendor-head-actions">${editAction}</div>`:''}</div><div class="vendor-view-content">${vendorView==='guide'?renderMaterialGuide():vendorView==='trade'?renderTradeVendors():vendorView==='sites'?renderSiteTradeVendors():renderOtherVendors()}</div>`;
}
window.setVendorView=function(v){vendorView=v;renderVendors();}
window.toggleVendorEditMode=function(){if(!isAdmin())return;vendorEditMode=!vendorEditMode;renderVendors();}
function activeMaterialGuide(){return materialGuides.find(x=>x.id===activeMaterialGuideId)||materialGuides[0];}
function renderMaterialGuide(){const item=activeMaterialGuide();if(item&&!activeMaterialGuideId)activeMaterialGuideId=item.id;return`<section class="guide-layout"><nav class="guide-nav">${materialGuides.map(x=>`<button class="${x.id===activeMaterialGuideId?'on':''}" onclick="selectMaterialGuide('${x.id}')">${escAttr(x.name)}</button>`).join('')}${isAdmin()&&guideEditing?'<button onclick="addMaterialGuide()">＋ 新增分類</button>':''}</nav><article class="guide-body">${item?`<div class="guide-title-row"><h2>${escAttr(item.name)}</h2>${isAdmin()&&guideEditing?`<span><button class="btn btn-sm" onclick="renameMaterialGuide('${item.id}')">重新命名</button> <button class="btn btn-sm btn-r" onclick="deleteMaterialGuide('${item.id}')">刪除</button></span>`:''}</div>${isAdmin()&&guideEditing?'<div class="guide-tools"><button class="btn btn-sm" onclick="document.execCommand(\'bold\')"><b>B</b></button><button class="btn btn-sm" onclick="document.execCommand(\'insertUnorderedList\')">• 列表</button><button class="btn btn-sm" onclick="document.execCommand(\'insertOrderedList\')">1. 列表</button><button class="btn btn-sm" title="文字顏色" onmousedown="event.preventDefault()" onclick="openGuideTextPalette(event)">A</button></div>':''}<div id="guide-content" class="guide-content" ${isAdmin()&&guideEditing?'contenteditable="true"':''}>${item.content}</div>${isAdmin()&&guideEditing?`<button class="btn btn-p" onclick="saveMaterialGuide('${item.id}')">儲存內容</button>`:''}`:'<div class="guide-empty">尚無分類內容</div>'}</article></section>`;}
window.openGuideTextPalette=function(e){document.getElementById('guide-text-palette')?.remove();const palette=document.createElement('div');palette.id='guide-text-palette';palette.className='meeting-color-palette';const swatch=color=>`<button type="button" class="meeting-palette-swatch" style="background:${color}" title="${color}" onmousedown="event.preventDefault()" onclick="pickGuideTextColor('${color}')"></button>`;palette.innerHTML=MEETING_COLOR_ROWS.map(row=>`<div class="meeting-palette-grid">${row.map(swatch).join('')}</div>`).join('')+`<div class="meeting-palette-standard">標準</div><div class="meeting-palette-grid">${MEETING_STANDARD_COLORS.map(swatch).join('')}</div><label class="meeting-palette-custom"><span>自訂</span><input type="color" value="#5c53ae" onchange="pickGuideTextColor(this.value)"></label>`;document.body.appendChild(palette);const rect=e.currentTarget.getBoundingClientRect(),pr=palette.getBoundingClientRect();palette.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-pr.width-8))+'px';palette.style.top=Math.max(8,Math.min(rect.bottom+6,window.innerHeight-pr.height-8))+'px';};window.pickGuideTextColor=function(color){document.execCommand('foreColor',false,color);document.getElementById('guide-text-palette')?.remove();};
window.selectMaterialGuide=function(id){activeMaterialGuideId=id;guideEditing=false;renderVendors();};window.toggleGuideEditing=function(){guideEditing=!guideEditing;renderVendors();};window.saveMaterialGuide=function(id){const item=materialGuides.find(x=>x.id===id);if(item)item.content=$('guide-content').innerHTML;localStorage.setItem('materialGuides',JSON.stringify(materialGuides));guideEditing=false;renderVendors();};window.addMaterialGuide=function(){const name=prompt('分類名稱')?.trim();if(!name)return;const item={id:'guide-'+Date.now(),name,content:'',sortOrder:materialGuides.length};if(localTestMode){materialGuides.push(item);activeMaterialGuideId=item.id;renderVendors();}else addDoc(collection(db,'materialGuides'),{...item,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});};window.renameMaterialGuide=function(id){const item=materialGuides.find(x=>x.id===id),name=prompt('分類名稱',item?.name||'')?.trim();if(item&&name){item.name=name;if(!localTestMode)updateDoc(doc(db,'materialGuides',id),{name,updatedAt:serverTimestamp()});renderVendors();}};window.deleteMaterialGuide=function(id){if(!confirm('確定刪除此分類？'))return;materialGuides=materialGuides.filter(x=>x.id!==id);activeMaterialGuideId=materialGuides[0]?.id||'';if(!localTestMode)deleteDoc(doc(db,'materialGuides',id));renderVendors();};
function projectTradeSelection(projectId,categoryId){
  const byProject=vendorProjectEditMode&&projectId===activeVendorProjectId?(vendorProjectDraft||{}):(S.projectTradeSelections[projectId]||{});
  return byProject[categoryId]||{vendorIds:[],none:false,notes:{}};
}
function projectTradeNeedsSetup(projectId){
  if(!S.tradeCategories.length)return true;
  const saved=S.projectTradeSelections[projectId]||{};
  return S.tradeCategories.some(function(category){
    const selection=saved[category.id];
    return !selection||(!selection.none&&!(selection.vendorIds||[]).length);
  });
}
function pendingTradeProjectsCount(){return S.projects.filter(p=>p.status==='prog'&&projectTradeNeedsSetup(p.id)).length;}
function renderSiteTradeVendors(){
  const projects=S.projects.filter(p=>p.status==='prog');
  if(!projects.length)return`<div class="empty">案件總覽目前沒有設定為「施工中」的工地。</div>`;
  if(!activeVendorProjectId||!projects.some(p=>p.id===activeVendorProjectId))activeVendorProjectId=projects[0].id;
  const project=projects.find(p=>p.id===activeVendorProjectId);
  return`<div style="display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px"><div class="ws-tabs" style="margin:0">${projects.map(p=>`<button class="ws-tab ${projectTradeNeedsSetup(p.id)?'needs-trade-setup':''} ${p.id===activeVendorProjectId?'active':''}" onclick="setActiveVendorProject('${p.id}')">${escAttr(p.name)}</button>`).join('')}</div><div style="display:flex;gap:6px">${vendorProjectEditMode?`<button class="btn btn-sm" onclick="cancelVendorProjectEdit()">取消</button><button class="btn btn-sm btn-p" onclick="saveVendorProjectTrades()">儲存</button>`:`<button class="btn btn-sm" onclick="startVendorProjectEdit()">✎ 編輯</button>`}</div></div><section class="site-vendor-project"><div class="site-vendor-project-hdr">${escAttr(project.name)}</div>${S.tradeCategories.map(c=>renderProjectTradeCategory(project,c)).join('')||'<div class="empty">請先建立施工工程項目</div>'}</section>`;
}
function renderProjectTradeCategory(project,category){
  const vendors=S.tradeVendors.filter(v=>v.categoryId===category.id),sel=projectTradeSelection(project.id,category.id),ids=sel.vendorIds||[],notes=sel.notes||{};
  const locked=!vendorProjectEditMode;
  const visibleVendors=locked?vendors.filter(v=>ids.includes(v.id)):vendors;
  return`<div class="site-vendor-category"><div class="site-vendor-category-title">${escAttr(category.name)}</div>${visibleVendors.map(v=>{const note=String(notes[v.id]||'').trim(),url=vendorSafeUrl(v.lineGroupUrl||''),lineValue=url?'':(v.lineId?`<span class="trade-vendor-muted">LINE ID：${escAttr(v.lineId)}</span>`:'—'),lineAction=url?`<button class="btn btn-sm" onclick="showVendorQr('${escAttr(url)}','${escAttr(v.companyName||'LINE 群組')}')">LINE群組</button>`:'';return`<div class="site-vendor-option"><label><input type="checkbox" ${ids.includes(v.id)?'checked':''} ${locked?'disabled':''} onchange="toggleProjectTradeVendor('${project.id}','${category.id}','${v.id}',this.checked)"><span>${escAttr(v.companyName||'未命名')}</span></label><div class="site-vendor-cell trade-vendor-muted">${escAttr(v.serviceItem||'—')}</div><div class="site-vendor-cell">${escAttr(v.contactName||'—')}</div><div class="site-vendor-cell trade-vendor-muted">${v.phone?escAttr(formatVendorPhone(v.phone)):'—'}</div><div class="site-vendor-cell trade-vendor-line">${lineValue}${lineAction?`<span class="trade-vendor-actions">${lineAction}</span>`:''}</div>${locked?(note?`<div class="site-vendor-note">${escAttr(note)}</div>`:''):`<input class="site-vendor-note-input" type="text" placeholder="此廠商負責範圍／備註" value="${escAttr(note)}" ${ids.includes(v.id)?'':'disabled'} oninput="saveProjectTradeNote('${project.id}','${category.id}','${v.id}',this.value)">`}</div>`;}).join('')}${!locked||sel.none?`<div class="site-vendor-option site-vendor-none"><label style="grid-column:1/-1"><input type="checkbox" ${sel.none?'checked':''} ${locked?'disabled':''} onchange="toggleProjectTradeNone('${project.id}','${category.id}',this.checked)"><strong>無</strong><span style="font-size:11px;color:var(--text3)">此工地沒有這項工程</span></label></div>`:''}</div>`;
}
function writeProjectTradeSelection(projectId,categoryId,next,rerender=true){
  if(!vendorProjectEditMode||projectId!==activeVendorProjectId)return;
  vendorProjectDraft={...(vendorProjectDraft||{}),[categoryId]:next};if(rerender)renderVendors();
}
window.setActiveVendorProject=function(id){activeVendorProjectId=id;vendorProjectEditMode=false;vendorProjectDraft=null;renderVendors();}
window.startVendorProjectEdit=function(){vendorProjectDraft=localClone(S.projectTradeSelections[activeVendorProjectId]||{});vendorProjectEditMode=true;renderVendors();}
window.cancelVendorProjectEdit=function(){vendorProjectEditMode=false;vendorProjectDraft=null;renderVendors();}
window.saveVendorProjectTrades=async function(){if(!vendorProjectEditMode||!activeVendorProjectId)return;setSyncing();S.projectTradeSelections={...(S.projectTradeSelections||{}),[activeVendorProjectId]:localClone(vendorProjectDraft||{})};await setDoc(doc(db,'projectTradeSelections',activeVendorProjectId),{categories:S.projectTradeSelections[activeVendorProjectId]});vendorProjectEditMode=false;vendorProjectDraft=null;setSynced();renderVendors();}
window.toggleProjectTradeVendor=function(projectId,categoryId,vendorId,checked){
  const cur=projectTradeSelection(projectId,categoryId),vendorIds=[...(cur.vendorIds||[])];
  const nextIds=checked?[...new Set([...vendorIds,vendorId])]:vendorIds.filter(id=>id!==vendorId);
  writeProjectTradeSelection(projectId,categoryId,{...cur,vendorIds:nextIds,none:checked?false:!!cur.none,notes:{...(cur.notes||{})}});
}
window.toggleProjectTradeNone=function(projectId,categoryId,checked){
  const cur=projectTradeSelection(projectId,categoryId);
  writeProjectTradeSelection(projectId,categoryId,{...cur,vendorIds:checked?[]:(cur.vendorIds||[]),none:checked,notes:{...(cur.notes||{})}});
}
window.saveProjectTradeNote=function(projectId,categoryId,vendorId,text){
  if(!vendorProjectEditMode)return;
  const cur=projectTradeSelection(projectId,categoryId),notes={...(cur.notes||{}),[vendorId]:(text||'').trim()};
  writeProjectTradeSelection(projectId,categoryId,{...cur,notes},false);
}
function sortTradeCategories(categories){return [...(categories||[])].sort((a,b)=>{const ao=Number.isFinite(Number(a.sortOrder))?Number(a.sortOrder):Number.MAX_SAFE_INTEGER;const bo=Number.isFinite(Number(b.sortOrder))?Number(b.sortOrder):Number.MAX_SAFE_INTEGER;return ao-bo;});}
let tradePointerDrag=null;
window.startTradeCategoryPointerDrag=function(e,id){if(e.button!==undefined&&e.button!==0)return;const group=e.currentTarget.closest('.vendor-group');if(!group)return;e.preventDefault();const placeholder=document.createElement('div');placeholder.className='vendor-group-placeholder';placeholder.style.height=group.offsetHeight+'px';group.parentNode.insertBefore(placeholder,group.nextSibling);group.classList.add('dragging');tradePointerDrag={id,group,placeholder};window.addEventListener('pointermove',moveTradeCategoryPointerDrag);window.addEventListener('pointerup',endTradeCategoryPointerDrag,{once:true});}
function moveTradeCategoryPointerDrag(e){const drag=tradePointerDrag;if(!drag)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.vendor-group[data-category-id]');if(!target||target===drag.group)return;const rect=target.getBoundingClientRect();target.parentNode.insertBefore(drag.placeholder,e.clientY<rect.top+rect.height/2?target:target.nextSibling);}
async function endTradeCategoryPointerDrag(){const drag=tradePointerDrag;if(!drag)return;window.removeEventListener('pointermove',moveTradeCategoryPointerDrag);drag.placeholder.parentNode.insertBefore(drag.group,drag.placeholder);drag.placeholder.remove();drag.group.classList.remove('dragging');tradePointerDrag=null;const ids=[...document.querySelectorAll('#panel-vendors .vendor-group[data-category-id]')].map(el=>el.dataset.categoryId);if(!ids.length)return;const ordered=ids.map(id=>S.tradeCategories.find(c=>c.id===id)).filter(Boolean).map((c,index)=>({...c,sortOrder:index}));if(ordered.map(c=>c.id).join('|')===sortTradeCategories(S.tradeCategories).map(c=>c.id).join('|'))return;S.tradeCategories=ordered;renderVendors();setSyncing();try{await Promise.all(ordered.map((c,index)=>updateDoc(doc(db,'tradeCategories',c.id),{sortOrder:index})));setSynced();}catch(error){console.error(error);setOffline();}}
window.moveTradeCategory=async function(id,direction){const ordered=sortTradeCategories(S.tradeCategories),from=ordered.findIndex(c=>c.id===id),to=from+direction;if(from<0||to<0||to>=ordered.length)return;const [moved]=ordered.splice(from,1);ordered.splice(to,0,moved);S.tradeCategories=ordered.map((c,index)=>({...c,sortOrder:index}));renderVendors();setSyncing();try{await Promise.all(S.tradeCategories.map((c,index)=>updateDoc(doc(db,'tradeCategories',c.id),{sortOrder:index})));setSynced();}catch(error){console.error(error);setOffline();}}
function renderTradeVendors(){
  const categories=sortTradeCategories(S.tradeCategories),canReorder=isAdmin()&&vendorEditMode;
  return`<div class="vendor-toolbar">${isAdmin()?'<button class="btn btn-p" onclick="showCategoryForm(\'trade\')">＋新增工程項目</button><button class="btn" onclick="showTradeVendorForm()">＋新增施工廠商</button>':''}<span style="font-size:11px;color:var(--text3)">${S.tradeCategories.length} 個工程項目 · ${S.tradeVendors.length} 家廠商</span></div>
  ${categories.length?categories.map((c,index)=>{const rows=S.tradeVendors.filter(v=>v.categoryId===c.id);return`<section class="vendor-group" data-category-id="${c.id}"><div class="vendor-group-hdr">${canReorder?`<span class="vendor-drag-handle" title="拖曳調整排序" onpointerdown="startTradeCategoryPointerDrag(event,'${c.id}')">⠿</span>`:''}<div class="vendor-group-title">${escAttr(c.name)}</div>${isAdmin()&&vendorEditMode?`<button class="btn btn-sm" title="上移" ${index===0?'disabled':''} onclick="moveTradeCategory('${c.id}',-1)">↑</button><button class="btn btn-sm" title="下移" ${index===categories.length-1?'disabled':''} onclick="moveTradeCategory('${c.id}',1)">↓</button><button class="btn btn-sm" onclick="renameVendorCategory('trade','${c.id}')">修改名稱</button><button class="btn btn-sm btn-danger" onclick="deleteVendorCategory('trade','${c.id}')">刪除</button>`:''}</div>${rows.length?rows.map(renderTradeVendorRow).join(''):'<div class="empty" style="padding:1rem">尚無廠商</div>'}</section>`;}).join(''):'<div class="empty">尚無工程項目，請先新增工程項目。</div>'}`;
}
function renderTradeVendorRow(v){
  const url=vendorSafeUrl(v.lineGroupUrl||'');
  const lineValue=url?'':(v.lineId?`<span class="trade-vendor-muted">LINE ID：${escAttr(v.lineId)}</span>`:'—');
  const lineActions=`${url?`<button class="btn btn-sm" onclick="showVendorQr('${escAttr(url)}','${escAttr(v.companyName||'LINE 群組')}')">LINE群組</button>`:''}${isAdmin()&&vendorEditMode?`<button class="btn btn-sm" onclick="showTradeVendorForm('${v.id}')">編輯</button><button class="btn btn-sm btn-danger" onclick="deleteTradeVendor('${v.id}')">刪除</button>`:''}`;
  return`<div class="vendor-row trade-vendor-row"><div class="trade-vendor-cell trade-vendor-company">${escAttr(v.companyName||'未命名')}</div><div class="trade-vendor-cell trade-vendor-muted">${escAttr(v.serviceItem||'—')}</div><div class="trade-vendor-cell">${escAttr(v.contactName||'—')}</div><div class="trade-vendor-cell trade-vendor-muted">${v.phone?escAttr(formatVendorPhone(v.phone)):'—'}</div><div class="trade-vendor-cell trade-vendor-line">${lineValue}${lineActions?`<span class="trade-vendor-actions">${lineActions}</span>`:''}</div></div>`;
}
function normalizedVendorName(name){return String(name||'').trim().replace(/\s+/g,'').toLowerCase();}
function matchingTradeVendors(name){const key=normalizedVendorName(name);return key?S.tradeVendors.filter(v=>normalizedVendorName(v.companyName)===key):[];}
window.filterTradeVendorSuggestions=function(query){const box=$('tv-company-suggestions');if(!box)return;const key=normalizedVendorName(query),seen=new Set(),matches=S.tradeVendors.filter(v=>{const name=normalizedVendorName(v.companyName);if(!name||seen.has(name)||!name.includes(key))return false;seen.add(name);return true;}).slice(0,8);box.innerHTML=key&&matches.length?matches.map(v=>`<button type="button" onclick="chooseTradeVendorProfile('${escAttr(v.id)}')"><strong>${escAttr(v.companyName)}</strong><small>${escAttr(v.contactName||'未填聯絡人')}${v.phone?'｜'+escAttr(formatVendorPhone(v.phone)):''}</small></button>`).join(''):'';}
window.chooseTradeVendorProfile=function(id){const v=S.tradeVendors.find(x=>x.id===id);if(!v)return;$('tv-company').value=v.companyName||'';$('tv-service').value=v.serviceItem||'';$('tv-contact').value=v.contactName||'';$('tv-phone').value=formatVendorPhone(v.phone||'');$('tv-line').value=v.lineId||'';$('tv-url').value=v.lineGroupUrl||'';$('tv-company-suggestions').innerHTML='';}
window.applyTradeVendorProfileFromCompany=function(){const company=$('tv-company')?.value||'',match=matchingTradeVendors(company)[0];if(match&&normalizedVendorName(company)===normalizedVendorName(match.companyName))chooseTradeVendorProfile(match.id);}
window.showTradeVendorForm=function(id,presetCategoryId){
  if(!isAdmin())return;const v=id?S.tradeVendors.find(x=>x.id===id):null;if(!S.tradeCategories.length)return alert('請先新增工程項目');
  $('mo-content').dataset.lockBackdrop='true';$('mo-content').innerHTML=`<div class="mo-title">${v?'編輯施工廠商':'新增施工廠商'}</div><div style="margin-top:12px;display:flex;flex-direction:column;gap:8px"><select id="tv-category">${S.tradeCategories.map(c=>`<option value="${c.id}" ${(v?.categoryId||presetCategoryId)===c.id?'selected':''}>${escAttr(c.name)}</option>`).join('')}</select><div class="vendor-company-search"><input id="tv-company" type="text" autocomplete="off" placeholder="輸入公司名稱搜尋或新增*" value="${escAttr(v?.companyName||'')}" oninput="filterTradeVendorSuggestions(this.value)" onchange="applyTradeVendorProfileFromCompany()"><div id="tv-company-suggestions" class="vendor-company-suggestions"></div></div><input id="tv-service" type="text" autocomplete="off" placeholder="服務項目" value="${escAttr(v?.serviceItem||'')}"><input id="tv-contact" type="text" autocomplete="off" placeholder="聯絡人" value="${escAttr(v?.contactName||'')}"><input id="tv-phone" type="text" autocomplete="off" inputmode="numeric" maxlength="11" placeholder="電話（例：0900-000000）" value="${escAttr(formatVendorPhone(v?.phone||''))}" oninput="formatVendorPhoneInput(this)"><input id="tv-line" type="text" autocomplete="off" placeholder="LINE ID" value="${escAttr(v?.lineId||'')}"><input id="tv-url" type="text" autocomplete="off" placeholder="LINE 群組邀請網址（https://…）" value="${escAttr(v?.lineGroupUrl||'')}"></div><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" onclick="saveTradeVendor(${v?`'${v.id}'`:'null'})">儲存</button></div>`;$('modal').style.display='flex';
}
window.saveTradeVendor=async function(id){
  const companyName=$('tv-company').value.trim(),lineGroupUrl=$('tv-url').value.trim(),existing=id?S.tradeVendors.find(v=>v.id===id):null;if(!companyName)return alert('請填寫公司名稱');if(lineGroupUrl&&!vendorSafeUrl(lineGroupUrl))return alert('請輸入有效的 http 或 https 網址');
  const shared={companyName,serviceItem:$('tv-service').value.trim(),contactName:$('tv-contact').value.trim(),phone:formatVendorPhone($('tv-phone').value),lineId:$('tv-line').value.trim(),lineGroupUrl,updatedAt:new Date().toISOString()},data={categoryId:$('tv-category').value,...shared};setSyncing();if(id){const sameCompany=matchingTradeVendors(existing?.companyName);await Promise.all(sameCompany.map(v=>updateDoc(doc(db,'tradeVendors',v.id),{...(v.id===id?{categoryId:data.categoryId}:{}),...shared})));}else await addDoc(collection(db,'tradeVendors'),{...data,createdAt:new Date().toISOString()});closeMo();setSynced();renderVendors();
}
window.deleteTradeVendor=async function(id){const v=S.tradeVendors.find(x=>x.id===id);if(!v||!confirm(`確定刪除「${v.companyName}」？`))return;await deleteDoc(doc(db,'tradeVendors',id));renderVendors();}
function renderOtherVendors(){
  const filtered=S.otherVendors.filter(v=>(otherVendorFilter==='all'||(v.categoryIds||[]).includes(otherVendorFilter))&&(!otherVendorSearch||(v.companyName||'').toLowerCase().includes(otherVendorSearch.toLowerCase())));
  return`<div class="vendor-toolbar">${isAdmin()?'<button class="btn btn-p" onclick="showOtherVendorForm()">＋新增其他廠商</button><button class="btn" onclick="showCategoryForm(\'other\')">＋新增類別</button>':''}<select onchange="setOtherVendorFilter(this.value)"><option value="all">全部類別</option>${S.otherVendorCategories.map(c=>`<option value="${c.id}" ${otherVendorFilter===c.id?'selected':''}>${escAttr(c.name)}</option>`).join('')}</select><input type="text" placeholder="搜尋公司名稱" value="${escAttr(otherVendorSearch)}" oninput="setOtherVendorSearch(this.value)"></div><div class="card"><div class="card-hdr"><span class="card-title">其他廠商（${filtered.length}）</span><button class="btn btn-sm" onclick="showOtherCategoryManager()">管理類別</button></div>${filtered.length?filtered.map(renderOtherVendorRow).join(''):'<div class="empty">沒有符合條件的廠商</div>'}</div>`;
}
function renderOtherVendorRow(v){const cats=(v.categoryIds||[]).map(id=>S.otherVendorCategories.find(c=>c.id===id)).filter(Boolean);return`<div class="vendor-row"><div class="vendor-main"><div class="vendor-name">${escAttr(v.companyName||'未命名')}</div><div class="vendor-tags">${cats.length?cats.map(c=>`<span class="vendor-tag">${escAttr(c.name)}</span>`).join(''):'<span class="vendor-tag" style="background:var(--bg);color:var(--text3)">未分類</span>'}</div>${v.note?`<div class="vendor-meta">${escAttr(v.note)}</div>`:''}</div>${isAdmin()?`<div class="vendor-actions"><button class="btn btn-sm" onclick="showOtherVendorForm('${v.id}')">編輯</button><button class="btn btn-sm btn-danger" onclick="deleteOtherVendor('${v.id}')">刪除</button></div>`:''}</div>`;}
window.setOtherVendorFilter=function(v){otherVendorFilter=v;renderVendors();};window.setOtherVendorSearch=function(v){otherVendorSearch=v;renderVendors();const inp=$('panel-vendors')?.querySelector('input[placeholder="搜尋公司名稱"]');if(inp){inp.focus();inp.setSelectionRange(v.length,v.length);}};
window.showOtherVendorForm=function(id){if(!isAdmin())return;const v=id?S.otherVendors.find(x=>x.id===id):null;$('mo-content').innerHTML=`<div class="mo-title">${v?'編輯其他廠商':'新增其他廠商'}</div><div style="margin-top:12px;display:flex;flex-direction:column;gap:8px"><div style="font-size:12px;color:var(--text2)">類別（可複選）</div><div class="vendor-checks">${S.otherVendorCategories.length?S.otherVendorCategories.map(c=>`<label class="vendor-check"><input type="checkbox" name="ov-category" value="${c.id}" ${(v?.categoryIds||[]).includes(c.id)?'checked':''}> ${escAttr(c.name)}</label>`).join(''):'尚無類別，請先新增類別'}</div><input id="ov-company" type="text" placeholder="公司名稱*" value="${escAttr(v?.companyName||'')}"><textarea id="ov-note" rows="4" placeholder="備註">${escAttr(v?.note||'')}</textarea></div><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" onclick="saveOtherVendor(${v?`'${v.id}'`:'null'})">儲存</button></div>`;$('modal').style.display='flex';}
window.saveOtherVendor=async function(id){const companyName=$('ov-company').value.trim();if(!companyName)return alert('請填寫公司名稱');const categoryIds=[...document.querySelectorAll('input[name="ov-category"]:checked')].map(x=>x.value);const data={companyName,categoryIds,note:$('ov-note').value.trim(),updatedAt:new Date().toISOString()};if(id)await updateDoc(doc(db,'otherVendors',id),data);else await addDoc(collection(db,'otherVendors'),{...data,createdAt:new Date().toISOString()});closeMo();renderVendors();}
window.deleteOtherVendor=async function(id){const v=S.otherVendors.find(x=>x.id===id);if(!v||!confirm(`確定刪除「${v.companyName}」？`))return;await deleteDoc(doc(db,'otherVendors',id));renderVendors();}
window.showCategoryForm=function(type){if(!isAdmin())return;$('mo-content').innerHTML=`<div class="mo-title">新增${type==='trade'?'工程項目':'其他廠商類別'}</div><div style="margin-top:12px"><input id="vc-name" type="text" placeholder="類別名稱*" onkeydown="if(event.key==='Enter')saveVendorCategory('${type}')"></div><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" onclick="saveVendorCategory('${type}')">新增</button></div>`;$('modal').style.display='flex';setTimeout(()=>$('vc-name')?.focus(),50);}
window.saveVendorCategory=async function(type){const name=$('vc-name').value.trim(),list=type==='trade'?S.tradeCategories:S.otherVendorCategories,collectionName=type==='trade'?'tradeCategories':'otherVendorCategories';if(!name)return alert('請輸入名稱');if(list.some(x=>x.name===name))return alert('已有相同名稱');const data={name,createdAt:new Date().toISOString()};if(type==='trade')data.sortOrder=sortTradeCategories(list).length;await addDoc(collection(db,collectionName),data);closeMo();renderVendors();}
window.renameVendorCategory=async function(type,id){const list=type==='trade'?S.tradeCategories:S.otherVendorCategories,c=list.find(x=>x.id===id);if(!c)return;const name=prompt('修改類別名稱',c.name)?.trim();if(!name||name===c.name)return;if(list.some(x=>x.id!==id&&x.name===name))return alert('已有相同名稱');await updateDoc(doc(db,type==='trade'?'tradeCategories':'otherVendorCategories',id),{name});renderVendors();}
window.deleteVendorCategory=async function(type,id){const isTrade=type==='trade',list=isTrade?S.tradeCategories:S.otherVendorCategories,c=list.find(x=>x.id===id);if(!c)return;const used=isTrade?S.tradeVendors.filter(v=>v.categoryId===id):S.otherVendors.filter(v=>(v.categoryIds||[]).includes(id));if(used.length)return alert(`「${c.name}」仍有 ${used.length} 家廠商使用，請先移除或改分類後再刪除。`);if(!confirm(`確定刪除類別「${c.name}」？`))return;await deleteDoc(doc(db,isTrade?'tradeCategories':'otherVendorCategories',id));if(!isTrade&&otherVendorFilter===id)otherVendorFilter='all';renderVendors();}
window.showOtherCategoryManager=function(){$('mo-content').innerHTML=`<div class="mo-title">其他廠商類別管理</div><div style="margin-top:12px">${S.otherVendorCategories.map(c=>`<div class="vendor-row" style="padding:8px 0"><div class="vendor-main">${escAttr(c.name)}</div>${isAdmin()?`<button class="btn btn-sm" onclick="closeMo();renameVendorCategory('other','${c.id}')">修改</button><button class="btn btn-sm btn-danger" onclick="closeMo();deleteVendorCategory('other','${c.id}')">刪除</button>`:''}</div>`).join('')||'<div class="empty">尚無類別</div>'}</div><div class="mo-footer">${isAdmin()?'<button class="btn btn-p" onclick="closeMo();showCategoryForm(\'other\')">＋新增類別</button>':''}<button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.openVendorUrl=function(url){const safe=vendorSafeUrl(url);if(safe)window.open(safe,'_blank','noopener');};window.copyVendorUrl=async function(url){try{await navigator.clipboard.writeText(url);alert('網址已複製');}catch(e){prompt('請複製網址',url);}};
window.showVendorQr=function(url,title){const safe=vendorSafeUrl(url);if(!safe)return;const qr='https://quickchart.io/qr?size=300&text='+encodeURIComponent(safe);$('mo-content').innerHTML=`<div class="mo-title">${escAttr(title)}</div><div class="qr-box"><img src="${qr}" alt="LINE 群組 QR Code"><div class="vendor-meta" style="margin-top:8px">掃描後開啟 LINE 群組邀請網址</div></div><div class="mo-footer"><button class="btn" onclick="copyVendorUrl('${escAttr(safe)}')">複製網址</button><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
