// Runtime-composed source module. Keep declarations in shared application scope.
let b1fView='inventory',b1fIssueProjectId='',b1fReturnProjectId='',b1fHistoryFilter='all',b1fStore=null,b1fFlash='';
const B1F_STORE_VERSION=2;
function b1fId(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);}
function b1fNow(){return new Date().toISOString();}
function b1fMoney(v){return '$'+Math.max(0,Number(v)||0).toLocaleString('zh-TW',{maximumFractionDigits:2});}
function b1fDateTime(v){const d=new Date(v);return isNaN(d)?'—':`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function b1fKey(){return `b1fStoreV2_${currentUser?.uid||'local'}`;}
function b1fSeed(){const now=b1fNow();return{version:B1F_STORE_VERSION,items:[
  {id:'b1-silicone',name:'白色矽利康',stockQty:6,unit:'條',unitPrice:0,source:'大塊森濤5F',note:'外箱略破',createdAt:now},
  {id:'b1-hinge',name:'BLUM 鉸鍊',stockQty:110,unit:'個',unitPrice:100,source:'公司常備',note:'',createdAt:now},
  {id:'b1-toilet',name:'HCG 馬桶',stockQty:1,unit:'個',unitPrice:5000,source:'林宅剩料',note:'可再次使用',createdAt:now}
],usages:[],logs:[]};}
function b1fData(){if(b1fStore)return b1fStore;try{const saved=JSON.parse(localStorage.getItem(b1fKey())||'null');b1fStore=saved?.version===B1F_STORE_VERSION?saved:b1fSeed();}catch(error){b1fStore=b1fSeed();}return b1fStore;}
function b1fSave(){localStorage.setItem(b1fKey(),JSON.stringify(b1fData()));}
function b1fItem(id){return b1fData().items.find(x=>x.id===id);}
function b1fUsage(id){return b1fData().usages.find(x=>x.id===id);}
function b1fOpenUsages(){return b1fData().usages.filter(x=>(Number(x.inUseQty)||0)>0);}
function b1fItemInUse(itemId){return b1fOpenUsages().filter(x=>x.itemId===itemId).reduce((n,x)=>n+(Number(x.inUseQty)||0),0);}
function b1fLog(type,data){b1fData().logs.push({id:b1fId('log'),type,createdAt:b1fNow(),actorId:currentUser?.uid||'',actorName:currentUser?.displayName||'',...data});}
function b1fTypeLabel(type){return({entry:'入庫',issue:'領用',charge:'計價',return:'退回',refund:'退款',used:'使用完畢',disposed:'報廢',inventory_disposed:'B1F直接報廢'})[type]||type;}
function b1fProjectOptions(selected,onlyWithUsage=false){let projects=S.projects.filter(p=>p.status==='prog');if(onlyWithUsage)projects=projects.filter(p=>b1fOpenUsages().some(r=>r.projectId===p.id));return`<option value="">請選擇案件</option>${projects.map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>${escAttr(p.name)}</option>`).join('')}`;}
function b1fInventoryMarkup(){const items=b1fData().items;return`<div class="b1f-list"><div class="b1f-list-head b1f-inventory-grid"><span>物品名稱</span><span class="b1f-col-center">在庫數量</span><span class="b1f-col-money">單價</span><span>來源</span><span class="b1f-col-center">使用中數量</span><span>備註</span><span class="b1f-col-center">操作</span></div>${items.length?items.map(i=>`<div class="b1f-row b1f-inventory-grid"><div class="b1f-item-name">${escAttr(i.name)}</div><div class="b1f-item-qty b1f-col-center">${i.stockQty}${escAttr(i.unit)}</div><div class="b1f-col-money">${b1fMoney(i.unitPrice)}</div><div class="b1f-cell-muted">${escAttr(i.source||'—')}</div><div class="b1f-col-center">${b1fItemInUse(i.id)?`${b1fItemInUse(i.id)}${escAttr(i.unit)}`:'—'}</div><div class="b1f-cell-muted">${escAttr(i.note||'—')}</div><div class="b1f-actions"><button class="btn btn-sm btn-p" ${i.stockQty>0?'':'disabled'} onclick="openB1FIssueFor('${i.id}')">領用</button><button class="btn btn-sm" ${i.stockQty>0?'':'disabled'} onclick="showB1FInventoryDispose('${i.id}')">報廢</button></div></div>`).join(''):'<div class="b1f-empty">目前沒有庫存物品。</div>'}</div>`;}
function b1fEntryMarkup(){return`<div class="card" style="max-width:700px"><div class="card-hdr"><span class="card-title">入庫</span></div><div class="b1f-form"><label class="b1f-field">物品名稱<input id="b1f-entry-name" placeholder="輸入物品名稱"></label><label class="b1f-field">數量<input id="b1f-entry-qty" type="number" min="0.01" step="any" placeholder="輸入數量"></label><label class="b1f-field">單位<input id="b1f-entry-unit" placeholder="例如：個、條、支" value="個"></label><label class="b1f-field">來源<input id="b1f-entry-source" placeholder="自由輸入來源"></label><label class="b1f-field">單價<input id="b1f-entry-price" type="number" min="0" step="any" placeholder="0 元物品請填 0"></label><label class="b1f-field">備註<textarea id="b1f-entry-note" placeholder="備註（選填）"></textarea></label><button class="btn btn-p" onclick="saveB1FEntry()">確認入庫</button></div></div>`;}
function b1fIssueMarkup(){const items=b1fData().items.filter(i=>Number(i.stockQty)>0);return`<div class="b1f-workflow"><label class="b1f-field b1f-workflow-head">使用工地／案件<select id="b1f-issue-project" onchange="setB1FIssueProject(this.value)">${b1fProjectOptions(b1fIssueProjectId)}</select></label><div class="b1f-pick-list">${items.length?items.map(i=>`<div class="b1f-pick-row"><input class="b1f-issue-check" type="checkbox" data-id="${i.id}" onchange="b1fTogglePick(this,'issue');b1fUpdateIssueSummary()"><div><strong>${escAttr(i.name)}</strong><div class="b1f-cell-muted">庫存 ${i.stockQty}${escAttr(i.unit)}</div></div><div class="b1f-pick-price b1f-col-money">${b1fMoney(i.unitPrice)}</div><div class="b1f-pick-price">小計 <span id="b1f-issue-sub-${i.id}">$0</span></div><label class="b1f-pick-qty">領用數量<input id="b1f-issue-qty-${i.id}" type="number" min="0" max="${i.stockQty}" step="any" value="0" disabled oninput="b1fUpdateIssueSummary()"></label></div>`).join(''):'<div class="b1f-empty">目前沒有可領用的庫存。</div>'}</div><div class="b1f-summary" id="b1f-issue-summary"><div class="b1f-cell-muted">勾選物品並輸入領用數量後，這裡會顯示摘要。</div></div><button class="btn btn-p" style="max-width:220px" onclick="confirmB1FIssue()">確認領用</button></div>`;}
function b1fReturnMarkup(){const records=b1fReturnProjectId?b1fOpenUsages().filter(r=>r.projectId===b1fReturnProjectId):[];return`<div class="b1f-workflow"><label class="b1f-field b1f-workflow-head">使用工地／案件<select onchange="setB1FReturnProject(this.value)">${b1fProjectOptions(b1fReturnProjectId,true)}</select></label>${b1fReturnProjectId?`<div class="b1f-pick-list">${records.map(r=>`<div class="b1f-pick-row"><input class="b1f-return-check" type="checkbox" data-id="${r.id}" onchange="b1fTogglePick(this,'return');b1fUpdateReturnSummary()"><div><strong>${escAttr(r.itemName)}</strong><div class="b1f-cell-muted">目前使用中 ${r.inUseQty}${escAttr(r.unit)}</div></div><div class="b1f-pick-price b1f-col-money">${b1fMoney(r.unitPrice)}</div><div class="b1f-pick-price">退款 <span id="b1f-return-sub-${r.id}">$0</span></div><label class="b1f-pick-qty">本次退回<input id="b1f-return-qty-${r.id}" type="number" min="0" max="${r.inUseQty}" step="any" value="0" disabled oninput="b1fUpdateReturnSummary()"></label></div>`).join('')||'<div class="b1f-empty">此案件目前沒有使用中物品。</div>'}</div><div class="b1f-summary" id="b1f-return-summary"><div class="b1f-cell-muted">勾選物品並輸入退回數量後，這裡會顯示退款摘要。</div></div><button class="btn btn-p" style="max-width:220px" onclick="confirmB1FReturn()">確認退回</button>`:'<div class="b1f-empty">請先選擇有 B1F 使用中物品的案件。</div>'}</div>`;}
function b1fInUseMarkup(){const records=b1fOpenUsages(),groups=[...new Set(records.map(r=>r.projectId))];if(!groups.length)return'<div class="b1f-empty">目前沒有使用中的 B1F 物品。</div>';return groups.map(pid=>{const rows=records.filter(r=>r.projectId===pid),project=S.projects.find(p=>p.id===pid);return`<section class="b1f-project-group"><div class="b1f-project-title">${escAttr(project?.name||rows[0].projectName||'未知案件')}</div>${rows.map(r=>`<div class="b1f-use-row"><div class="b1f-item-name">${escAttr(r.itemName)}</div><div class="b1f-item-qty">${r.inUseQty}${escAttr(r.unit)}</div><div class="b1f-col-money">${b1fMoney(r.unitPrice)}</div><div class="b1f-use-meta b1f-cell-muted">原始計價 ${b1fMoney(r.chargeAmount)}｜已退款 ${b1fMoney(r.refundedAmount)}</div><div class="b1f-actions"><button class="btn btn-sm btn-p" onclick="showB1FUsageAction('${r.id}','used')">使用完畢</button><button class="btn btn-sm" onclick="openB1FReturnFor('${r.projectId}')">退回</button><button class="btn btn-sm btn-danger" onclick="showB1FUsageAction('${r.id}','disposed')">報廢</button></div></div>`).join('')}</section>`;}).join('');}
function b1fHistoryMarkup(){let logs=b1fData().logs.slice().reverse();if(b1fHistoryFilter!=='all'){if(b1fHistoryFilter==='disposed')logs=logs.filter(x=>['disposed','inventory_disposed'].includes(x.type));else logs=logs.filter(x=>x.type===b1fHistoryFilter);}return`<div class="seg" style="width:max-content;margin-bottom:10px">${[['all','全部'],['entry','入庫'],['issue','領用'],['return','退回'],['used','使用完畢'],['disposed','報廢']].map(([id,label])=>`<button class="${b1fHistoryFilter===id?'on':''}" onclick="setB1FHistoryFilter('${id}')">${label}</button>`).join('')}</div><div class="b1f-list"><div class="b1f-list-head b1f-history-grid"><span>日期</span><span>類型</span><span>物品</span><span class="b1f-col-center">數量</span><span>案件／來源</span><span class="b1f-col-money">金額</span></div>${logs.length?logs.map(x=>`<div class="b1f-row b1f-history-grid"><div class="b1f-cell-muted">${b1fDateTime(x.createdAt)}</div><div>${b1fTypeLabel(x.type)}</div><div class="b1f-item-name">${escAttr(x.itemName||'—')}</div><div class="b1f-col-center">${x.quantity??'—'}${x.unit?escAttr(x.unit):''}</div><div class="b1f-cell-muted">${escAttr(x.projectName||x.source||'B1F')}</div><div class="b1f-col-money">${x.amount==null?'—':b1fMoney(x.amount)}</div></div>`).join(''):'<div class="b1f-empty">尚無異動紀錄。</div>'}</div>`;}
function renderB1F(){const el=$('panel-b1f');if(!el)return;const tabs=[['entry','入庫'],['inventory','庫存'],['issue','領用'],['return','退回'],['inuse','使用中'],['history','紀錄']],views={entry:b1fEntryMarkup,inventory:b1fInventoryMarkup,issue:b1fIssueMarkup,return:b1fReturnMarkup,inuse:b1fInUseMarkup,history:b1fHistoryMarkup};el.innerHTML=`<div class="b1f-shell"><div class="b1f-head"><div><h1>🛒 B1F 商城</h1><p>工程剩料、可再利用物品與常備五金；計價只記錄在 B1F 與工地使用紀錄。</p></div><div class="b1f-tabs">${tabs.map(([id,label])=>`<button class="${b1fView===id?'active':''}" onclick="setB1FView('${id}')">${label}</button>`).join('')}</div></div>${b1fFlash?`<div class="b1f-summary" style="margin-bottom:12px">${escAttr(b1fFlash)}</div>`:''}${views[b1fView]()}</div>`;b1fFlash='';}
window.renderB1F=renderB1F;
window.setB1FView=function(view){b1fView=view;renderB1F();};
window.setB1FIssueProject=function(projectId){b1fIssueProjectId=projectId;};
window.setB1FReturnProject=function(projectId){b1fReturnProjectId=projectId;renderB1F();};
window.setB1FHistoryFilter=function(filter){b1fHistoryFilter=filter;renderB1F();};
window.b1fTogglePick=function(box,type){const input=$(`b1f-${type}-qty-${box.dataset.id}`);if(input){input.disabled=!box.checked;if(!box.checked)input.value=0;else if(Number(input.value)<=0)input.value=1;}};
window.b1fUpdateIssueSummary=function(){let total=0,html='';document.querySelectorAll('.b1f-issue-check:checked').forEach(box=>{const item=b1fItem(box.dataset.id),qty=Number($(`b1f-issue-qty-${item.id}`).value)||0,amount=qty*item.unitPrice;total+=amount;$(`b1f-issue-sub-${item.id}`).textContent=b1fMoney(amount);if(qty>0)html+=`<div class="b1f-summary-row"><span>${escAttr(item.name)} ×${qty}</span><strong>${b1fMoney(amount)}</strong></div>`;});$('b1f-issue-summary').innerHTML=(html||'<div class="b1f-cell-muted">尚未選擇有效數量。</div>')+`<div class="b1f-summary-row b1f-summary-total"><span>本次計價總額</span><span>${b1fMoney(total)}</span></div>`;};
window.b1fUpdateReturnSummary=function(){let total=0,html='';document.querySelectorAll('.b1f-return-check:checked').forEach(box=>{const r=b1fUsage(box.dataset.id),qty=Number($(`b1f-return-qty-${r.id}`).value)||0,amount=qty*r.unitPrice;total+=amount;$(`b1f-return-sub-${r.id}`).textContent=b1fMoney(amount);if(qty>0)html+=`<div class="b1f-summary-row"><span>${escAttr(r.itemName)} ×${qty}</span><strong>退款 ${b1fMoney(amount)}</strong></div>`;});$('b1f-return-summary').innerHTML=(html||'<div class="b1f-cell-muted">尚未選擇有效數量。</div>')+`<div class="b1f-summary-row b1f-summary-total"><span>本次退款總額</span><span>${b1fMoney(total)}</span></div>`;};
window.saveB1FEntry=function(){const name=$('b1f-entry-name').value.trim(),qty=Number($('b1f-entry-qty').value),unit=$('b1f-entry-unit').value.trim(),source=$('b1f-entry-source').value.trim(),price=Number($('b1f-entry-price').value),note=$('b1f-entry-note').value.trim();if(!name||!unit||!Number.isFinite(qty)||qty<=0||!Number.isFinite(price)||price<0)return alert('請完整填寫物品名稱、正確數量、單位與單價。');const item={id:b1fId('item'),name,stockQty:qty,unit,unitPrice:price,source,note,createdAt:b1fNow()};b1fData().items.push(item);b1fLog('entry',{itemId:item.id,itemName:name,quantity:qty,unit,source,amount:qty*price});b1fSave();b1fView='inventory';renderB1F();};
window.confirmB1FIssue=function(){const project=S.projects.find(p=>p.id===$('b1f-issue-project').value);if(!project)return alert('請選擇施工中案件。');const lines=[];document.querySelectorAll('.b1f-issue-check:checked').forEach(box=>{const item=b1fItem(box.dataset.id),qty=Number($(`b1f-issue-qty-${item.id}`).value);lines.push({item,qty});});if(!lines.length)return alert('請至少勾選一項物品。');if(lines.some(x=>!Number.isFinite(x.qty)||x.qty<=0||x.qty>x.item.stockQty))return alert('每項領用數量必須大於 0，且不得超過在庫數量。');const batchId=b1fId('batch'),now=b1fNow();lines.forEach(({item,qty})=>{item.stockQty-=qty;const amount=qty*item.unitPrice,record={id:b1fId('usage'),batchId,itemId:item.id,itemName:item.name,unit:item.unit,unitPrice:item.unitPrice,projectId:project.id,projectName:project.name,issuedQty:qty,inUseQty:qty,returnedQty:0,usedQty:0,disposedQty:0,chargeAmount:amount,refundedAmount:0,status:'in_use',issuedAt:now};b1fData().usages.push(record);b1fLog('issue',{batchId,usageId:record.id,itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,projectId:project.id,projectName:project.name,amount});if(amount>0)b1fLog('charge',{batchId,usageId:record.id,itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,projectId:project.id,projectName:project.name,amount});});b1fSave();b1fFlash=`領用完成：${lines.length} 項｜本次計價總額 ${b1fMoney(lines.reduce((n,x)=>n+x.qty*x.item.unitPrice,0))}`;b1fView='inuse';renderB1F();};
window.confirmB1FReturn=function(){const lines=[];document.querySelectorAll('.b1f-return-check:checked').forEach(box=>{const record=b1fUsage(box.dataset.id),qty=Number($(`b1f-return-qty-${record.id}`).value);lines.push({record,qty});});if(!lines.length)return alert('請至少勾選一項退回物品。');if(lines.some(x=>!Number.isFinite(x.qty)||x.qty<=0||x.qty>x.record.inUseQty))return alert('每項退回數量必須大於 0，且不得超過目前使用中數量。');lines.forEach(({record,qty})=>{const item=b1fItem(record.itemId),refund=qty*record.unitPrice;record.inUseQty-=qty;record.returnedQty+=qty;record.refundedAmount+=refund;record.status=record.inUseQty>0?'in_use':'closed';item.stockQty+=qty;b1fLog('return',{usageId:record.id,itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,projectId:record.projectId,projectName:record.projectName,amount:refund});if(refund>0)b1fLog('refund',{usageId:record.id,itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,projectId:record.projectId,projectName:record.projectName,amount:refund});});b1fSave();b1fFlash=`退回完成｜本次退款總額 ${b1fMoney(lines.reduce((n,x)=>n+x.qty*x.record.unitPrice,0))}`;b1fView='inuse';renderB1F();};
window.openB1FIssueFor=function(itemId){b1fView='issue';renderB1F();setTimeout(()=>{const box=document.querySelector(`.b1f-issue-check[data-id="${itemId}"]`);if(box){box.checked=true;b1fTogglePick(box,'issue');b1fUpdateIssueSummary();}},0);};
window.openB1FReturnFor=function(projectId){b1fReturnProjectId=projectId;b1fView='return';renderB1F();};
window.showB1FInventoryDispose=function(itemId){const item=b1fItem(itemId);if(!item)return;$('mo-content').innerHTML=`<div class="mo-title">B1F 直接報廢：${escAttr(item.name)}</div><div class="b1f-form"><label class="b1f-field">本次報廢數量<input id="b1f-action-qty" type="number" min="0.01" max="${item.stockQty}" step="any" value="1"></label><label class="b1f-field">備註<textarea id="b1f-action-note" placeholder="報廢原因（選填）"></textarea></label><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-danger" onclick="confirmB1FInventoryDispose('${item.id}')">確認報廢</button></div></div>`;$('modal').style.display='flex';};
window.confirmB1FInventoryDispose=function(itemId){const item=b1fItem(itemId),qty=Number($('b1f-action-qty').value);if(!item||!Number.isFinite(qty)||qty<=0||qty>item.stockQty)return alert('報廢數量必須大於 0，且不得超過在庫數量。');item.stockQty-=qty;b1fLog('inventory_disposed',{itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,source:item.source,amount:null,note:$('b1f-action-note').value.trim()});b1fSave();closeMo();renderB1F();};
window.showB1FUsageAction=function(usageId,type){const r=b1fUsage(usageId),label=type==='used'?'使用完畢':'報廢';if(!r)return;$('mo-content').innerHTML=`<div class="mo-title">${label}：${escAttr(r.itemName)}</div><div class="b1f-form"><div class="mo-sub">目前使用中 ${r.inUseQty}${escAttr(r.unit)}；可處理部分數量。</div><label class="b1f-field">本次${label}數量<input id="b1f-action-qty" type="number" min="0.01" max="${r.inUseQty}" step="any" value="${r.inUseQty}"></label><label class="b1f-field">備註<textarea id="b1f-action-note" placeholder="備註（選填）"></textarea></label><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn ${type==='disposed'?'btn-danger':'btn-p'}" onclick="confirmB1FUsageAction('${r.id}','${type}')">確認${label}</button></div></div>`;$('modal').style.display='flex';};
window.confirmB1FUsageAction=function(usageId,type){const r=b1fUsage(usageId),qty=Number($('b1f-action-qty').value);if(!r||!Number.isFinite(qty)||qty<=0||qty>r.inUseQty)return alert('數量必須大於 0，且不得超過目前使用中數量。');r.inUseQty-=qty;if(type==='used')r.usedQty+=qty;else r.disposedQty+=qty;r.status=r.inUseQty>0?'in_use':'closed';b1fLog(type,{usageId:r.id,itemId:r.itemId,itemName:r.itemName,quantity:qty,unit:r.unit,projectId:r.projectId,projectName:r.projectName,amount:null,note:$('b1f-action-note').value.trim()});b1fSave();closeMo();renderB1F();};
function b1fProjectHistoryMarkup(projectId){const records=b1fData().usages.filter(r=>r.projectId===projectId);if(!records.length)return'';const total=records.reduce((n,r)=>n+r.chargeAmount-r.refundedAmount,0);return`<section class="b1f-project-history"><h3>🛒 B1F 商城使用紀錄</h3>${records.map(r=>{const actual=r.issuedQty-r.returnedQty,status=r.inUseQty>0?`使用中 ${r.inUseQty}${r.unit}`:r.disposedQty>0&&r.usedQty===0?'報廢':r.returnedQty===r.issuedQty?'已退回':'使用完畢';return`<div class="b1f-project-history-row"><span>${escAttr(r.itemName)}｜領用${r.issuedQty}${escAttr(r.unit)}${r.returnedQty?`｜退回${r.returnedQty}${escAttr(r.unit)}`:''}｜實際${actual}${escAttr(r.unit)}</span><strong>${status}${r.unitPrice>0?`｜${b1fMoney(r.chargeAmount-r.refundedAmount)}`:''}</strong></div>`;}).join('')}<div class="b1f-project-total">B1F 實際總計：${b1fMoney(total)}</div></section>`;}
