// Runtime-composed source module. Keep declarations in shared application scope.
// ── B1F 商城 V5：Firebase 公司共用庫存，購物車維持個人暫存 ──
const B1F_SHARED_VERSION=6,B1F_SHARED_DOC='company';
let b1fPersonalCart=null;
function b1fSharedRef(){return doc(db,'b1fStores',B1F_SHARED_DOC);}
function b1fCartKeyV5(){return `b1fCartV5_${currentUser?.uid||'local'}`;}
function b1fNormalizeShared(raw){const base=b1fSeedV3();return{...base,...(raw||{}),version:B1F_SHARED_VERSION,items:Array.isArray(raw?.items)?raw.items.map(item=>({...item,categoryIds:Array.isArray(item.categoryIds)?item.categoryIds:[]})):[],categories:Array.isArray(raw?.categories)?raw.categories:[],usages:Array.isArray(raw?.usages)?raw.usages:[],logs:Array.isArray(raw?.logs)?raw.logs:[],orders:Array.isArray(raw?.orders)?raw.orders:[],carts:{}};}
function b1fLoadPersonalCart(){if(b1fPersonalCart)return b1fPersonalCart;try{const rows=JSON.parse(localStorage.getItem(b1fCartKeyV5())||'null');b1fPersonalCart=Array.isArray(rows)?rows:[];}catch(error){b1fPersonalCart=[];}return b1fPersonalCart;}
function b1fPersistPersonalCart(){try{localStorage.setItem(b1fCartKeyV5(),JSON.stringify(b1fLoadPersonalCart()));}catch(error){console.warn('B1F 購物車暫存失敗',error);}}
function b1fDataV5(){if(localTestMode)return b1fDataV3();return b1fStore||b1fNormalizeShared(null);}
function b1fCartV5(){if(!localTestMode)return b1fLoadPersonalCart();const data=b1fDataV3(),uid=currentUser?.uid||'local';data.carts||(data.carts={});return(data.carts[uid]||=([]));}
function b1fSaveCartV5(){if(localTestMode){b1fSaveV3();return;}b1fPersistPersonalCart();}
function b1fLogIn(store,type,data){store.logs.push({id:b1fId('log'),type,createdAt:b1fNow(),actorId:currentUser?.uid||'',actorName:currentUser?.displayName||'',...data});}
async function b1fCommit(change){
  if(localTestMode){const result=change(b1fDataV3());b1fSaveV3();return result;}
  setSyncing();
  try{return await fbRunTransaction(db,async transaction=>{const snap=await transaction.get(b1fSharedRef()),store=b1fNormalizeShared(snap.exists()?snap.data():null),result=change(store);transaction.set(b1fSharedRef(),{version:B1F_SHARED_VERSION,items:store.items,categories:store.categories,usages:store.usages,logs:store.logs,orders:store.orders,updatedAt:serverTimestamp()});return result;});}
  catch(error){console.error('B1F 同步失敗',error);setOffline();alert('B1F 商城同步失敗，請確認網路後再試。');throw error;}
  finally{if(!localTestMode)setSynced();}
}
function initB1FSharedStore(){
  if(localTestMode)return;
  onSnapshot(b1fSharedRef(),snap=>{b1fStore=b1fNormalizeShared(snap.exists()?snap.data():null);if(activePanel==='b1f')renderB1F();},error=>{console.error('B1F 同步讀取失敗',error);setOffline();});
}
b1fData=b1fDataV5;b1fCart=b1fCartV5;b1fSave=b1fSaveCartV5;
window.addB1FToCart=function(itemId){const item=b1fItem(itemId),input=$(`b1f-product-qty-${itemId}`),qty=Number(input?.value);if(!item||!Number.isFinite(qty)||qty<=0||qty>item.stockQty)return alert('本次數量必須大於 0，且不得超過庫存。');const cart=b1fCart(),line=cart.find(x=>x.itemId===itemId),next=(line?.qty||0)+qty;if(next>item.stockQty)return alert(`${item.name} 加入後會超過目前庫存 ${item.stockQty}${item.unit}。`);if(line)line.qty=next;else cart.push({itemId,qty});b1fSaveCartV5();b1fFlash=`已加入購物車：${item.name} ×${qty}${item.unit}`;renderB1F();};
window.changeB1FCartQty=function(itemId,delta){const line=b1fCart().find(x=>x.itemId===itemId),item=b1fItem(itemId);if(!line||!item)return;line.qty=Math.max(1,Math.min(item.stockQty,line.qty+delta));b1fSaveCartV5();renderB1F();};
window.setB1FCartQty=function(itemId,value){const line=b1fCart().find(x=>x.itemId===itemId),item=b1fItem(itemId),qty=Number(value);if(!line||!item)return;if(!Number.isFinite(qty)||qty<=0||qty>item.stockQty)return alert(`數量必須介於 1 到 ${item.stockQty}${item.unit}。`);line.qty=qty;b1fSaveCartV5();renderB1F();};
window.removeB1FCartItem=function(itemId){const cart=b1fCart(),index=cart.findIndex(x=>x.itemId===itemId);if(index>=0){cart.splice(index,1);b1fSaveCartV5();renderB1F();}};
window.saveB1FEntry=async function(){const name=$('b1f-entry-name').value.trim(),qty=Number($('b1f-entry-qty').value),unit=$('b1f-entry-unit').value.trim(),source=$('b1f-entry-source').value.trim(),price=Number($('b1f-entry-price').value),note=$('b1f-entry-note').value.trim();if(!name||!unit||!Number.isFinite(qty)||qty<=0||!Number.isFinite(price)||price<0)return alert('請完整填寫商品名稱、正確數量、單位與單價。');const item={id:b1fId('item'),name,stockQty:qty,unit,unitPrice:price,source,note,createdAt:b1fNow()};try{await b1fCommit(store=>{store.items.push(item);b1fLogIn(store,'entry',{itemId:item.id,itemName:name,quantity:qty,unit,source,amount:qty*price});});b1fView='entry';b1fFlash=`已新增商品：${name}`;renderB1F();}catch(error){}};
window.startEditB1FProductName=function(itemId,el){if(!isAdmin())return;const item=b1fItem(itemId);if(!item)return;el.innerHTML=`<input type="text" value="${escAttr(item.name)}" style="width:100%;box-sizing:border-box;font:inherit;font-size:14px;font-weight:650;padding:3px 6px;border:1px solid var(--purple);border-radius:4px" onclick="event.stopPropagation()" onkeydown="event.stopPropagation();if(event.key==='Enter'&&!event.isComposing&&event.keyCode!==229){this.blur();}if(event.key==='Escape'){this.value='';this.blur();}" onblur="saveB1FProductName('${itemId}',this.value)">`;const input=el.querySelector('input');input.focus();input.select();};
window.saveB1FProductName=async function(itemId,value){if(!isAdmin())return;const item=b1fItem(itemId),name=(value||'').trim();if(!item||!name||name===item.name){renderB1F();return;}try{await b1fCommit(store=>{const target=store.items.find(row=>row.id===itemId);if(target)target.name=name;});b1fFlash='商品名稱已更新';renderB1F();}catch(error){}};
window.saveB1FEntry=async function(){const name=$('b1f-entry-name').value.trim(),categoryIds=[...document.querySelectorAll('input[name="b1f-entry-category"]:checked')].map(input=>input.value),qty=Number($('b1f-entry-qty').value),unit=$('b1f-entry-unit').value.trim(),source=$('b1f-entry-source').value.trim(),price=Number($('b1f-entry-price').value),note=$('b1f-entry-note').value.trim();if(!name||!unit||!Number.isFinite(qty)||qty<=0||!Number.isFinite(price)||price<0)return alert('請完整填寫商品名稱、正確數量、單位與單價。');const item={id:b1fId('item'),name,categoryIds,stockQty:qty,unit,unitPrice:price,source,note,createdAt:b1fNow()};try{await b1fCommit(store=>{item.categoryIds=categoryIds.filter(id=>store.categories.some(category=>category.id===id));store.items.push(item);b1fLogIn(store,'entry',{itemId:item.id,itemName:name,quantity:qty,unit,source,amount:qty*price});});b1fView='entry';b1fFlash=`已新增商品：${name}`;renderB1F();}catch(error){}};
window.saveB1FCategory=async function(){if(!isAdmin())return;const name=$('b1f-category-name')?.value.trim();if(!name)return alert('請輸入分類名稱。');try{await b1fCommit(store=>{store.categories||(store.categories=[]);if(store.categories.some(category=>category.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase()))throw new Error('已有相同分類名稱。');store.categories.push({id:b1fId('category'),name,createdAt:b1fNow()});});b1fFlash=`已新增分類：${name}`;renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.renameB1FCategory=async function(id){if(!isAdmin())return;const category=b1fCategories().find(row=>row.id===id),name=prompt('修改分類名稱',category?.name||'')?.trim();if(!category||!name||name===category.name)return;try{await b1fCommit(store=>{if(store.categories.some(row=>row.id!==id&&row.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase()))throw new Error('已有相同分類名稱。');const target=store.categories.find(row=>row.id===id);if(target)target.name=name;});b1fFlash='分類名稱已更新';renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.deleteB1FCategory=async function(id){if(!isAdmin())return;const category=b1fCategories().find(row=>row.id===id);if(!category||!confirm(`確定刪除分類「${category.name}」？此分類會一併從相關商品移除。`))return;try{await b1fCommit(store=>{store.categories=store.categories.filter(row=>row.id!==id);store.items.forEach(item=>{item.categoryIds=(item.categoryIds||[]).filter(categoryId=>categoryId!==id);});});b1fFlash=`已刪除分類：${category.name}`;renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.showB1FProductCategories=function(itemId){if(!isAdmin())return;const item=b1fItem(itemId);if(!item)return;$('mo-content').innerHTML=`<div class="mo-title">設定分類：${escAttr(item.name)}</div><div style="margin-top:12px"><div class="b1f-category-checks">${b1fCategoryChecks('b1f-product-category',item.categoryIds)}</div></div><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" onclick="saveB1FProductCategories('${itemId}')">儲存分類</button></div>`;$('modal').style.display='flex';};
window.saveB1FProductCategories=async function(itemId){if(!isAdmin())return;const categoryIds=[...document.querySelectorAll('input[name="b1f-product-category"]:checked')].map(input=>input.value);try{await b1fCommit(store=>{const item=store.items.find(row=>row.id===itemId);if(!item)return;item.categoryIds=categoryIds.filter(id=>store.categories.some(category=>category.id===id));});closeMo();b1fFlash='商品分類已更新';renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.confirmB1FCart=async function(){const project=S.projects.find(p=>p.id===$('b1f-cart-project')?.value),cartLines=b1fCart().map(line=>({...line}));if(!project)return alert('請選擇施工中案件。');if(!cartLines.length)return alert('購物車目前沒有商品。');try{const result=await b1fCommit(store=>{const lines=cartLines.map(line=>({line,item:store.items.find(item=>item.id===line.itemId)}));const invalid=lines.find(x=>!x.item||!Number.isFinite(x.line.qty)||x.line.qty<=0||x.line.qty>x.item.stockQty);if(invalid)throw new Error(invalid?.item?`${invalid.item.name} 目前庫存不足，請調整數量後再確認。`:'商品已不存在。');const batchId=b1fId('batch'),now=b1fNow(),order={id:b1fId('order'),batchId,orderNo:`B1F-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${String(store.orders.filter(o=>String(o.orderNo||'').startsWith(`B1F-${new Date().toISOString().slice(0,10).replaceAll('-','')}-`)).length+1).padStart(3,'0')}`,projectId:project.id,projectName:project.name,createdAt:now,actorId:currentUser?.uid||'',actorName:currentUser?.displayName||'',usageIds:[]};lines.forEach(({line,item})=>{item.stockQty-=line.qty;const amount=line.qty*item.unitPrice,record={id:b1fId('usage'),batchId,orderId:order.id,orderNo:order.orderNo,itemId:item.id,itemName:item.name,unit:item.unit,unitPrice:item.unitPrice,projectId:project.id,projectName:project.name,issuedQty:line.qty,inUseQty:line.qty,returnedQty:0,usedQty:0,disposedQty:0,chargeAmount:amount,refundedAmount:0,status:'pending',issuedAt:now};store.usages.push(record);order.usageIds.push(record.id);b1fLogIn(store,'issue',{batchId,orderId:order.id,usageId:record.id,itemId:item.id,itemName:item.name,quantity:line.qty,unit:item.unit,projectId:project.id,projectName:project.name,amount});if(amount>0)b1fLogIn(store,'charge',{batchId,orderId:order.id,usageId:record.id,itemId:item.id,itemName:item.name,quantity:line.qty,unit:item.unit,projectId:project.id,projectName:project.name,amount});});store.orders.push(order);return{order,total:lines.reduce((sum,x)=>sum+x.line.qty*x.item.unitPrice,0)};});const cart=b1fCart();cart.splice(0,cart.length);if(!localTestMode)b1fPersonalCart=cart;b1fSaveCartV5();b1fFlash=`訂單 ${result.order.orderNo} 已完成｜本次總金額 ${b1fMoney(result.total)}`;b1fView='pending';renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.confirmB1FReturn=async function(){const picked=[...document.querySelectorAll('.b1f-return-check:checked')].map(box=>({id:box.dataset.id,qty:Number($(`b1f-return-qty-${box.dataset.id}`).value)}));if(!picked.length)return alert('請至少勾選一項退貨商品。');try{const result=await b1fCommit(store=>{const rows=picked.map(line=>({line,record:store.usages.find(row=>row.id===line.id)})),invalid=rows.find(x=>!x.record||!Number.isFinite(x.line.qty)||x.line.qty<=0||x.line.qty>x.record.inUseQty);if(invalid)throw new Error('部分商品的待結案數量已變更，請重新確認後再送出。');let total=0;rows.forEach(({line,record})=>{const item=store.items.find(x=>x.id===record.itemId),refund=line.qty*record.unitPrice;if(!item)throw new Error('商品資料不存在，無法完成退貨。');record.inUseQty-=line.qty;record.returnedQty+=line.qty;record.refundedAmount+=refund;record.status=record.inUseQty>0?'pending':'closed';item.stockQty+=line.qty;total+=refund;b1fLogIn(store,'return',{orderId:record.orderId,usageId:record.id,itemId:item.id,itemName:item.name,quantity:line.qty,unit:item.unit,projectId:record.projectId,projectName:record.projectName,amount:refund});if(refund>0)b1fLogIn(store,'refund',{orderId:record.orderId,usageId:record.id,itemId:item.id,itemName:item.name,quantity:line.qty,unit:item.unit,projectId:record.projectId,projectName:record.projectName,amount:refund});});return total;});b1fFlash=`退貨完成｜本次退款總額 ${b1fMoney(result)}`;b1fView='pending';renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.confirmB1FInventoryDispose=async function(itemId){if(!b1fCanDispose())return;const qty=Number($('b1f-action-qty').value),note=$('b1f-action-note').value.trim();try{await b1fCommit(store=>{const item=store.items.find(x=>x.id===itemId);if(!item||!Number.isFinite(qty)||qty<=0||qty>item.stockQty)throw new Error('報廢數量必須大於 0，且不得超過目前庫存。');item.stockQty-=qty;b1fLogIn(store,'inventory_disposed',{itemId:item.id,itemName:item.name,quantity:qty,unit:item.unit,source:item.source,amount:null,note});});closeMo();b1fFlash='B1F 庫存已報廢';renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.confirmB1FUsageAction=async function(usageId,type){if(type==='disposed'&&!b1fCanDispose())return;const qty=Number($('b1f-action-qty').value),note=$('b1f-action-note').value.trim();try{await b1fCommit(store=>{const r=store.usages.find(x=>x.id===usageId);if(!r||!Number.isFinite(qty)||qty<=0||qty>r.inUseQty)throw new Error('數量必須大於 0，且不得超過目前待結案數量。');r.inUseQty-=qty;if(type==='used')r.usedQty+=qty;else r.disposedQty+=qty;r.status=r.inUseQty>0?'pending':'closed';b1fLogIn(store,type,{orderId:r.orderId,usageId:r.id,itemId:r.itemId,itemName:r.itemName,quantity:qty,unit:r.unit,projectId:r.projectId,projectName:r.projectName,amount:null,note});});closeMo();b1fFlash=`已完成${type==='used'?'使用完畢':'報廢'}`;renderB1F();}catch(error){if(error?.message)alert(error.message);}};
window.bulkB1FUseFinished=async function(projectId){const ids=[...document.querySelectorAll('.b1f-used-check:checked')].filter(box=>box.dataset.project===projectId).map(box=>box.dataset.id);if(!ids.length)return alert('請至少勾選一項商品。');try{const count=await b1fCommit(store=>{let changed=0;ids.forEach(id=>{const row=store.usages.find(x=>x.id===id),qty=Number(row?.inUseQty)||0;if(qty<=0)return;row.inUseQty=0;row.usedQty=(Number(row.usedQty)||0)+qty;row.status='closed';b1fLogIn(store,'used',{orderId:row.orderId,usageId:row.id,itemId:row.itemId,itemName:row.itemName,quantity:qty,unit:row.unit,projectId:row.projectId,projectName:row.projectName,amount:null});changed++;});if(!changed)throw new Error('選取商品已被其他人處理，請重新整理資料。');return changed;});b1fFlash=`已完成 ${count} 項商品使用完畢`;renderB1F();}catch(error){if(error?.message)alert(error.message);}};
