import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
const now=new Date(),fetchedAt=now.toISOString(),day=86400000,headers={'user-agent':'InteriorControlNewsBot/1.0 (+https://github.com/havenspacedesign-coder/interior-control)'};
const gvm=[['國際',['world']],['AI／科技',['AI','tech']],['金融／產經',['money','business']],['好享生活／教育／話題',['life','education','issue']]];
const apple=[['國際','international',1],['生活','life',1],['社會','local',1],['娛樂時尚','entertainment',1],['AI科技／3C','aitech',1],['財經股市','finance',1],['推薦／熱門','hit',2]];
const get=async url=>{const r=await fetch(url,{headers,signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`${r.status} ${url}`);return r.text();};
const decode=s=>String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&quot;/g,'"').trim();
const norm=s=>decode(s).normalize('NFKC').replace(/\s+/g,' ').toLowerCase();
function make(source,category,o){const title=decode(o.headline||o.title),url=String(o.url||o.link||''),image=Array.isArray(o.image)?o.image[0]:o.image,imageUrl=String(o.imageUrl||image?.url||image||''),publishedAt=new Date(o.datePublished||o.pubDate||'');if(!title||!url||!imageUrl||Number.isNaN(+publishedAt))return null;return{id:createHash('sha1').update(url).digest('hex').slice(0,16),source,category,title,url,imageUrl,publishedAt:publishedAt.toISOString(),fetchedAt};}
function articles(v,out=[]){if(Array.isArray(v))v.forEach(x=>articles(x,out));else if(v&&typeof v==='object'){if([].concat(v['@type']).includes('Article')&&(v.headline||v.name))out.push(v);Object.values(v).forEach(x=>{if(x&&typeof x==='object')articles(x,out);});}return out;}
function gvmParse(html,category){const raw=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi))try{raw.push(...articles(JSON.parse(m[1])));}catch{}return raw.map(x=>make('遠見',category,x)).filter(Boolean);}
const tag=(s,n)=>decode(s.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`,'i'))?.[1]);
function appleParse(xml,category){return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>make('壹蘋',category,{title:tag(m[1],'title'),link:tag(m[1],'link'),pubDate:tag(m[1],'pubDate'),imageUrl:m[1].match(/<media:(?:content|thumbnail)\b[^>]*\burl=["']([^"']+)/i)?.[1]})).filter(Boolean);}
const unique=items=>{const u=new Set(),t=new Set();return items.filter(x=>!u.has(x.url)&&!t.has(norm(x.title))&&(u.add(x.url),t.add(norm(x.title)),true));};
function pick(candidates,chosen,count,fallback=[]){const used=new Set(chosen.map(x=>x.url)),titles=new Set(chosen.map(x=>norm(x.title))),available=x=>unique(x).filter(i=>!used.has(i.url)&&!titles.has(norm(i.title))),age=i=>now-new Date(i.publishedAt),selected=[];for(const pool of[available(candidates).filter(i=>age(i)>=0&&age(i)<=day),available(candidates).filter(i=>age(i)>=0&&age(i)<=2*day),available(fallback),available(candidates)])for(const item of pool.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt))){if(selected.length>=count||used.has(item.url)||titles.has(norm(item.title)))continue;selected.push(item);used.add(item.url);titles.add(norm(item.title));}return selected;}
const gp=await Promise.all(gvm.map(async([category,paths])=>({category,items:unique((await Promise.all(paths.map(p=>get(`https://www.gvm.com.tw/category/${p}`).then(h=>gvmParse(h,category)).catch(()=>[])))).flat())})));
const ap=await Promise.all(apple.map(async([category,path,count])=>({category,count,items:await get(`https://news.nextapple.com/api/rss/category/${path}`).then(x=>appleParse(x,category)).catch(()=>[])})));
let news=[];const gf=gp.flatMap(x=>x.items),af=ap.find(x=>x.category==='推薦／熱門')?.items||[];for(const p of gp)news.push(...pick(p.items,news,1,gf));for(const p of ap)news.push(...pick(p.items,news,p.count,af));const all=unique([...ap.flatMap(x=>x.items),...gf]);if(news.length<12)news.push(...pick(all,news,12-news.length,all));news=unique(news).slice(0,12);if(news.length<12)throw Error(`只取得 ${news.length} 則不重複新聞，保留既有 news.json。`);const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);await writeFile(new URL('../news.json',import.meta.url),JSON.stringify({date,updatedAt:fetchedAt,news},null,2)+'\n');console.log(`news.json 已更新：${news.length} 則`);
