// Runtime-composed source module. Keep declarations in shared application scope.
// ── Company announcements ──
let announcementHomePage=0;
function announcementMillis(value){return homeNoteMillis(value);}
function announcementDate(value){if(!value)return'—';if(/^\d{4}-\d{2}-\d{2}$/.test(String(value))){const [year,month,day]=String(value).split('-');return`${Number(month)}/${Number(day)}/${year}`;}const ms=announcementMillis(value);return ms?new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'numeric',day:'numeric'}).format(new Date(ms)):'—';}
function announcementDateTime(value){const ms=announcementMillis(value);return ms?new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms)):'—';}
function announcementPublishMillis(item){return announcementMillis(item?.publishedAt)||announcementMillis(item?.createdAt)||new Date(`${item?.publishDate||''}T00:00:00`).getTime()||0;}
function sortedAnnouncements(){return S.announcements.slice().sort((a,b)=>announcementPublishMillis(b)-announcementPublishMillis(a));}
function announcementDateParts(item){const value=item?.publishDate||item?.publishedAt||item?.createdAt;if(/^\d{4}-\d{2}-\d{2}$/.test(String(value||''))){const [year,month,day]=String(value).split('-');return{monthDay:`${Number(month)}.${String(Number(day)).padStart(2,'0')}`,year};}const ms=announcementMillis(value);if(!ms)return{monthDay:'—',year:''};const date=new Date(ms);return{monthDay:`${date.getMonth()+1}.${String(date.getDate()).padStart(2,'0')}`,year:String(date.getFullYear())};}
function renderAnnouncementsModule(){const items=sortedAnnouncements(),pageCount=Math.max(1,Math.ceil(items.length/3));announcementHomePage=Math.max(0,Math.min(announcementHomePage,pageCount-1));const pageItems=items.slice(announcementHomePage*3,announcementHomePage*3+3),rows=pageItems.map(item=>{const date=announcementDateParts(item),content=escAttr(item.content);return`<article class="a1-announcement-row" onclick="event.stopPropagation();showAnnouncementsPage()"><div class="a1-announcement-date"><div class="a1-announcement-day">${escAttr(date.monthDay)}</div><div class="a1-announcement-year">${escAttr(date.year)}</div></div><div class="a1-announcement-copy"><div class="a1-announcement-title-text">${escAttr(item.title)}</div><div class="a1-announcement-excerpt" title="${content}"><span class="a1-announcement-excerpt-track"><span>${content}</span><span aria-hidden="true">${content}</span></span></div></div><span class="a1-announcement-arrow" aria-hidden="true">›</span></article>`;}).join('');return`<div class="a1-announcements"><div class="a1-announcement-top"><div><div class="a1-announcement-title">公司公告</div><div class="a1-announcement-subtitle">COMPANY NEWS</div></div><div class="a1-brand-squares" aria-label="品牌色彩"><span></span><span></span><span></span><span></span><span></span></div><div class="a1-brand-line">Have spare time to settle your mind,<br>Haven space to settle your life.</div></div>${pageItems.length?`<div class="a1-announcement-list a1-announcement-list-${pageItems.length}">${rows}</div>`:'<div class="a1-empty">目前尚無公司公告</div>'}<div class="a1-announcement-foot"><button class="a1-view-all" onclick="event.stopPropagation();showAnnouncementsPage()">查看全部 →</button><span class="a1-count">${items.length?`${announcementHomePage*3+1}–${Math.min(announcementHomePage*3+3,items.length)} / ${items.length}`:''}</span>${pageCount>1?`<span class="announcement-page-controls"><button class="btn" aria-label="上一組公告" ${announcementHomePage===0?'disabled':''} onclick="event.stopPropagation();moveAnnouncementPage(-1)">‹</button><button class="btn" aria-label="下一組公告" ${announcementHomePage===pageCount-1?'disabled':''} onclick="event.stopPropagation();moveAnnouncementPage(1)">›</button></span>`:''}</div></div>`;}
window.moveAnnouncementPage=function(delta){const count=Math.max(1,Math.ceil(S.announcements.length/3));announcementHomePage=Math.max(0,Math.min(count-1,announcementHomePage+delta));renderHome();}
function renderAnnouncementCard(item){return`<article class="announcement-card"><div class="announcement-card-head"><h2 class="announcement-card-title">${escAttr(item.title)}</h2>${isAdmin()?`<div class="announcement-card-tools"><button class="btn btn-sm" onclick="showAnnouncementForm('${item.id}')">編輯</button><button class="btn btn-sm btn-danger" onclick="deleteAnnouncement('${item.id}')">刪除</button></div>`:''}</div><div class="announcement-card-content">${escAttr(item.content)}</div><div class="announcement-card-meta"><span>發布日期：${escAttr(announcementDate(item.publishDate||item.publishedAt))}</span><span>生效日期：${escAttr(announcementDate(item.effectiveDate))}</span><span>建立人：${escAttr(item.createdByName||'—')}</span><span>最後更新：${escAttr(announcementDateTime(item.updatedAt||item.createdAt))}</span></div><div class="announcement-like"><button class="btn" onclick="likeAnnouncement('${item.id}')">👍 讚 ${Number(item.likeCount)||0}</button></div></article>`;}
function renderAnnouncementsModal(){const items=sortedAnnouncements();$('mo-content').className='mo-box announcement-modal';$('mo-content').innerHTML=`<div class="mo-title">公司公告</div><div class="mo-sub">最新發布的公告會顯示在最上方，所有歷史公告均會保留。</div><div class="announcement-list">${items.length?items.map(renderAnnouncementCard).join(''):'<div class="empty">目前尚無公司公告。</div>'}</div><div class="mo-footer">${isAdmin()?'<button class="btn btn-p" onclick="showAnnouncementForm()">＋新增公告</button>':''}<button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.showAnnouncementsPage=function(){renderAnnouncementsModal();}
function announcementToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
window.showAnnouncementForm=function(id){if(!isAdmin())return;const item=id?S.announcements.find(row=>row.id===id):null;if(id&&!item)return;const effective=item?.effectiveDate||announcementToday();$('mo-content').className='mo-box';$('mo-content').style.maxWidth='700px';$('mo-content').innerHTML=`<div class="mo-title">${item?'編輯公司公告':'新增公司公告'}</div><div class="mo-sub">發布日期會在儲存時自動記錄；生效日期可自行設定。</div><div class="announcement-form"><label>公告標題<input id="announcement-title" maxlength="120" placeholder="輸入公告標題" value="${escAttr(item?.title||'')}"></label><label>公告內容<textarea id="announcement-content" rows="8" maxlength="5000" placeholder="輸入完整公告內容">${escAttr(item?.content||'')}</textarea></label><label>生效日期<input id="announcement-effective-date" type="date" value="${escAttr(effective)}"></label></div><div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" onclick="saveAnnouncement(${item?`'${item.id}'`:'null'})">儲存公告</button></div>`;$('modal').style.display='flex';}
window.saveAnnouncement=async function(id){if(!isAdmin()||!currentUser)return;const title=$('announcement-title')?.value.trim()||'',content=$('announcement-content')?.value.trim()||'',effectiveDate=$('announcement-effective-date')?.value||'';if(!title||!content||!effectiveDate)return alert('請填寫公告標題、內容與生效日期。');const now=localTestMode?new Date().toISOString():serverTimestamp(),data={title,content,effectiveDate,updatedAt:now};try{if(id)await updateDoc(doc(db,'announcements',id),data);else await addDoc(collection(db,'announcements'),{...data,publishDate:announcementToday(),publishedAt:now,createdAt:now,createdBy:currentUser.uid,createdByName:currentUser.displayName||currentUser.email||'管理員',likeCount:0});closeMo();renderHome();}catch(error){console.error('announcement save failed',error);alert('公告暫時無法儲存，請稍後再試。');}}
window.deleteAnnouncement=async function(id){if(!isAdmin())return;const item=S.announcements.find(row=>row.id===id);if(!item||!confirm(`確定刪除公告「${item.title}」？此操作無法復原。`))return;try{await deleteDoc(doc(db,'announcements',id));renderAnnouncementsModal();}catch(error){console.error('announcement deletion failed',error);alert('公告暫時無法刪除，請稍後再試。');}}
window.likeAnnouncement=async function(id){const item=S.announcements.find(row=>row.id===id);if(!item)return;try{if(localTestMode){item.likeCount=(Number(item.likeCount)||0)+1;localStorage.setItem('localPreviewAnnouncements',JSON.stringify(S.announcements));if($('modal').style.display==='flex')renderAnnouncementsModal();else renderHome();return;}await fbRunTransaction(db,async tx=>{const ref=doc(db,'announcements',id),snap=await tx.get(ref);if(!snap.exists())throw new Error('公告不存在');tx.update(ref,{likeCount:(Number(snap.data().likeCount)||0)+1});});}catch(error){console.error('announcement like failed',error);alert('按讚暫時無法完成，請稍後再試。');}}
