// Runtime-composed source module. Keep declarations in shared application scope.
// ── Daily joke module ──
async function initTodayNews(){if(todayNewsLoading||todayNews)return;todayNewsLoading=true;try{const response=await fetch(new URL('news.json',window.__APP_BASE_URL__||location.href),{cache:'no-store'});if(!response.ok)throw new Error(`news ${response.status}`);const data=await response.json();todayNews={...data,news:Array.isArray(data?.news)?data.news.filter(item=>safeNewsUrl(item?.url)&&safeNewsUrl(item?.imageUrl)):[]};todayNewsSlide=Math.min(todayNewsSlide,Math.max(0,todayNews.news.length-1));}catch(error){console.warn('today news unavailable',error);todayNews={news:[]};}finally{todayNewsLoading=false;if(activePanel==='home')renderHome();}}
function todayNewsUpdateLabel(value){const date=new Date(value);if(Number.isNaN(date.valueOf()))return'每日早晨更新';return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}).format(date)+' 更新';}
function safeNewsUrl(value){try{const url=new URL(String(value||''));return['http:','https:'].includes(url.protocol)?url.href:'';}catch{return'';}}
const HAVEN_PRIMARY=[['classic','經典多欄版'],['hero','大圖頭版'],['columns','三欄新聞版'],['briefing','主新聞＋快訊版'],['asym','不對稱刊物版']],HAVEN_EXTRA=[['ledger','策展欄版'],['gallery','視覺索引版']];let havenTemplateOffset=0;
function havenTemplate(){const n=Math.floor(Date.now()/86400000)+havenTemplateOffset;return HAVEN_PRIMARY[((n%HAVEN_PRIMARY.length)+HAVEN_PRIMARY.length)%HAVEN_PRIMARY.length];}
function havenTemplateSheet(id,large=false){const copy=[['A Room for Quiet Living','Natural materials, warm daylight and thoughtful proportions shape a quieter rhythm for everyday life. This home is designed around comfort, clarity and the beauty of useful space.'],['Design Notes for Modern Homes','Small details make a lasting difference in the way a place feels. Honest textures, balanced lighting and careful storage create rooms that remain calm, flexible and welcoming.'],['A Better Home, A Brighter Day','Ideas, people and inspiring spaces gathered for the week ahead. We explore how considered interiors support better routines, meaningful connections and a more comfortable future.']];return`<div class="haven-template-sheet ${escAttr(id)}${large?' large':''}"><b class="hvs-brand">HAVEN DAILY · SEPTEMBER 07, 2026</b><b class="hvs-title">THE DAILY NEWS</b><b class="hvs-world">WORLD NEWS TODAY · DESIGN · ARCHITECTURE · ISSUE 028</b><i class="hvs-mast"></i><i class="hvs-date"></i><i class="hvs-photo"></i><i class="hvs-photo b"></i><i class="hvs-photo c"></i>${copy.map((x,i)=>`<span class="hvs-copy ${['a','b','c'][i]}">${x[0]}<small>${x[1]}</small></span>`).join('')}</div>`;}
function havenStory(item,index,withImage=false){return`<button class="haven-story haven-brief" onclick="event.stopPropagation();showHavenNews(${index})">${withImage?`<img class="haven-photo" src="${escAttr(safeNewsUrl(item.imageUrl))}" alt="">`:''}<span class="haven-kicker">${String(index+1).padStart(2,'0')} · ${escAttr(item.source||'有隅')}</span><span class="haven-brief-title">${escAttr(item.title)}</span></button>`;}
function renderTodayNewsModule(tier,m){if(todayNewsLoading&&!todayNews)return'<div class="today-news-loading">有隅特報載入中…</div>';const items=Array.isArray(todayNews?.news)?todayNews.news:[];if(!items.length)return'<div class="today-news-empty">有隅特報準備中</div>';const[id]=havenTemplate(),compact=(m?.w||3)<=3||(m?.h||3)<=3,lead=items[0],rest=items.slice(1,compact?3:6),date=new Intl.DateTimeFormat('zh-TW',{month:'2-digit',day:'2-digit',weekday:'short'}).format(new Date());const feature=`<div class="haven-feature"><img class="haven-photo" src="${escAttr(safeNewsUrl(lead.imageUrl))}" alt="${escAttr(lead.title)}"><div class="haven-feature-copy"><div class="haven-kicker">TOP STORY · ${escAttr(lead.category||'設計觀點')}</div><div class="haven-headline">${escAttr(lead.title)}</div><div class="haven-deck">${escAttr(lead.source||'有隅特報')} · 點擊閱讀完整 12 則新聞</div></div></div>`,briefs=`<div class="haven-side">${rest.map((x,i)=>havenStory(x,i+1,id==='gallery')).join('')}</div>`;return`<div class="haven-paper haven-${id}" data-compact="${compact}" role="button" tabindex="0" onclick="if(!homeEditMode)showHavenNews()"><div class="haven-mast"><span>HAVEN DAILY</span><span class="haven-mast-title">有隅特報</span><span class="haven-mast-meta">${date} · ${escAttr(todayNewsUpdateLabel(todayNews.updatedAt))} · VOL.${String((new Date().getDate()%99)+1).padStart(3,'0')}<br>DESIGN A BETTER HOME</span></div><div class="haven-layout">${feature}${briefs}</div></div>`;}
window.moveTodayNews=function(delta){const count=Array.isArray(todayNews?.news)?todayNews.news.length:0;if(!count)return;todayNewsSlide=(todayNewsSlide+delta+count)%count;renderHome();}
window.showHavenNews=function(focus=0){const items=Array.isArray(todayNews?.news)?todayNews.news:[];$('mo-content').className='mo-box haven-news-modal';$('mo-content').innerHTML=`<div class="mo-title">有隅特報</div><div class="mo-sub">今日完整 ${items.length} 則新聞。縮圖為 A4 版面結構：淺灰區為圖片，灰線為欄線與報頭。</div><div class="haven-template-gallery">${[...HAVEN_PRIMARY,...HAVEN_EXTRA].map(([id,name])=>`<button class="haven-template-preview" onclick="showHavenTemplate('${id}','${escAttr(name)}')">${havenTemplateSheet(id)}<span>${escAttr(name)}</span></button>`).join('')}</div><div class="haven-news-full-grid">${items.map((item,index)=>`<a class="haven-news-full-card ${index===focus?'focus':''}" href="${escAttr(safeNewsUrl(item.url))}" target="_blank" rel="noopener noreferrer"><img src="${escAttr(safeNewsUrl(item.imageUrl))}" alt="${escAttr(item.title)}"><span class="haven-news-full-copy"><span class="haven-news-full-title">${String(index+1).padStart(2,'0')}　${escAttr(item.title)}</span></span></a>`).join('')}</div><div class="mo-footer"><button class="btn" onclick="nextHavenTemplate()">下一個模板</button><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.nextHavenTemplate=function(){havenTemplateOffset=(havenTemplateOffset+1)%HAVEN_PRIMARY.length;closeMo();renderHome();};window.showHavenTemplate=function(id,name){$('mo-content').innerHTML=`<div class="mo-title">${name}｜完整灰階模板稿</div><div class="mo-sub">保留完整報頭、日期／期數與右上標語的位置；灰塊代表新聞照片、灰線代表各欄分隔。</div>${havenTemplateSheet(id,true)}<div class="mo-footer"><button class="btn" onclick="showHavenNews()">返回模板列表</button></div>`;};window.showTodayNewsGallery=function(){showHavenNews(todayNewsSlide);}
function jokeDayKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function jokeReactionOptions(){return[{id:'laugh',emoji:'🤣',label:'超好笑'},{id:'cold',emoji:'🥶',label:'好冷'},{id:'bad',emoji:'😑',label:'超難笑'}];}
function jokeCurrentVote(){return currentUser?jokeVotes.find(v=>v.uid===currentUser.uid):null;}
function jokeVoteCount(reaction){return jokeVotes.filter(v=>v.reaction===reaction).length;}
function renderDailyJokeModule(tier){
  if(jokeLoading&&!todayJoke)return'<div class="daily-joke-loading">今日笑話載入中…</div>';
  if(!todayJoke)return`<div class="daily-joke-empty">今日笑話準備中${isSystemAdmin()?'<br><button class="btn btn-sm" style="margin-top:8px" onclick="event.stopPropagation();replaceTodayJoke()">取得一則</button>':''}</div>`;
  const mine=jokeCurrentVote();
  return`<div class="daily-joke"><div class="daily-joke-title">${escAttr(todayJoke.title||'今日笑話')}</div><div class="daily-joke-content">${escAttr(todayJoke.content||'')}</div><div class="daily-joke-reactions">${jokeReactionOptions().map(r=>`<button class="joke-reaction ${mine?.reaction===r.id?'active':''}" onclick="event.stopPropagation();voteDailyJoke('${r.id}')"><span>${r.emoji}</span><span class="joke-reaction-label">${r.label}</span><span class="joke-vote-count" onclick="event.stopPropagation();showJokeVoters('${r.id}')">${jokeVoteCount(r.id)}</span></button>`).join('')}${isSystemAdmin()?`<span class="daily-joke-admin"><button class="btn" onclick="event.stopPropagation();replaceTodayJoke()">換一則</button><button class="btn" onclick="event.stopPropagation();showCustomJokeLibrary()">笑話庫</button></span>`:''}</div></div>`;
}
function pickDifferentJoke(pool){const alternatives=pool.filter(item=>item.content!==todayJoke?.content),choices=alternatives.length?alternatives:pool;return choices[Math.floor(Math.random()*choices.length)];}
function loadBuiltinJokes(){if(jokeLibraryPromise)return jokeLibraryPromise;jokeLibraryPromise=fetch(new URL('assets/daily-jokes.json',window.__APP_BASE_URL__||location.href),{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`daily jokes ${response.status}`);return response.json();}).then(data=>{const rows=Array.isArray(data?.jokes)?data.jokes:[];builtinJokes=rows.filter(item=>String(item?.text||'').trim()).map(item=>({id:`builtin-${String(item.id||'').trim()}`,title:String(item.category||'每日笑話').trim()||'每日笑話',content:String(item.text).trim(),source:'builtin-library',sourceRef:String(item.id||'').trim()}));return builtinJokes;}).catch(error=>{console.warn('built-in joke library unavailable',error);builtinJokes=[];return builtinJokes;});return jokeLibraryPromise;}
function dailyJokePool(){return[...builtinJokes,...customJokes].filter(item=>String(item?.content||'').trim());}
async function localJokePick(){await loadBuiltinJokes();const pool=dailyJokePool().length?dailyJokePool():LOCAL_JOKE_FALLBACKS,pick=pickDifferentJoke(pool);return{title:pick.title||'今日笑話',content:pick.content,source:pick.source||'local-fallback',sourceRef:pick.sourceRef||pick.id||''};}
async function fetchTianJoke(){
  const response=await fetch('/api/joke',{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`joke api ${response.status}`);
  const data=await response.json();if(!data?.content)throw new Error(data?.message||'joke api empty');return{title:data.title||'今日笑話',content:data.content,source:'tianapi',sourceRef:data.sourceRef||''};
}
async function chooseNewJoke(){return localJokePick();}
function makeJokeRecord(joke,reason){const day=jokeDayKey(),id=`joke-${day}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;return{id,day,title:joke.title||'今日笑話',content:joke.content,source:joke.source||'fallback',sourceRef:joke.sourceRef||'',reason,createdBy:currentUser?.uid||'',createdByName:currentUser?.displayName||currentUser?.email||'',createdAt:serverTimestamp()};}
async function ensureTodayJoke(){
  if(jokeLoading||todayJoke)return;jokeLoading=true;if(activePanel==='home')renderHome();
  try{
    const day=jokeDayKey();
    if(localTestMode){const record=makeJokeRecord(await localJokePick(),'daily');record.createdAt=new Date().toISOString();todayJoke=record;jokeVotes=[];return;}
    const dailyRef=doc(db,'dailyJokes',day),existing=await getDoc(dailyRef);if(existing.exists())return;
    const chosen=await chooseNewJoke(),record=makeJokeRecord(chosen,'daily'),jokeRef=doc(db,'jokes',record.id);
    await fbRunTransaction(db,async tx=>{const latest=await tx.get(dailyRef);if(latest.exists())return;tx.set(jokeRef,record);tx.set(dailyRef,{day,currentJokeId:record.id,updatedAt:serverTimestamp(),reason:'daily'});});
  }catch(error){console.error('daily joke creation failed',error);}finally{jokeLoading=false;if(activePanel==='home')renderHome();}
}
function subscribeJokeRecord(jokeId){
  if(jokeDocUnsub)jokeDocUnsub();if(jokeVotesUnsub)jokeVotesUnsub();todayJoke=null;jokeVotes=[];
  if(!jokeId){ensureTodayJoke();return;}
  jokeDocUnsub=onSnapshot(doc(db,'jokes',jokeId),snap=>{todayJoke=snap.exists()?{id:snap.id,...snap.data()}:null;if(activePanel==='home')renderHome();});
  jokeVotesUnsub=onSnapshot(query(collection(db,'jokeVotes'),where('jokeId','==',jokeId)),snap=>{jokeVotes=snap.docs.map(d=>({id:d.id,...d.data()}));if(activePanel==='home')renderHome();});
}
function initDailyJoke(){
  if(localTestMode){if(!todayJoke)ensureTodayJoke();return;}
  const day=jokeDayKey();if(jokeDailyUnsub)jokeDailyUnsub();jokeDailyUnsub=onSnapshot(doc(db,'dailyJokes',day),snap=>{if(snap.exists())subscribeJokeRecord(snap.data().currentJokeId);else ensureTodayJoke();},error=>{console.error('daily joke listener failed',error);});
  if(jokeCustomUnsub)jokeCustomUnsub();jokeCustomUnsub=onSnapshot(collection(db,'customJokes'),snap=>{customJokes=snap.docs.map(d=>({id:d.id,...d.data()}));});
}
window.replaceTodayJoke=async function(){
  if(!isSystemAdmin()||jokeLoading)return;jokeLoading=true;if(activePanel==='home')renderHome();
  try{const chosen=await chooseNewJoke(),record=makeJokeRecord(chosen,'manual');if(localTestMode){todayJoke={...record,createdAt:new Date().toISOString()};jokeVotes=[];}else{await setDoc(doc(db,'jokes',record.id),record);await setDoc(doc(db,'dailyJokes',jokeDayKey()),{day:jokeDayKey(),currentJokeId:record.id,updatedAt:serverTimestamp(),reason:'manual',changedBy:currentUser.uid});}}catch(error){console.error(error);alert('暫時無法更換笑話，請稍後再試。');}finally{jokeLoading=false;if(activePanel==='home')renderHome();}
}
window.voteDailyJoke=async function(reaction){
  if(!currentUser||!todayJoke||!jokeReactionOptions().some(r=>r.id===reaction))return;const vote={jokeId:todayJoke.id,uid:currentUser.uid,userName:currentUser.displayName||currentUser.email||memberDisplayName(S.members.find(m=>m.uid===currentUser.uid)),reaction,updatedAt:serverTimestamp()};
  if(localTestMode){const old=jokeVotes.find(v=>v.uid===currentUser.uid);if(old)Object.assign(old,vote);else jokeVotes.push({...vote,id:`${todayJoke.id}_${currentUser.uid}`});renderHome();return;}
  await setDoc(doc(db,'jokeVotes',`${todayJoke.id}_${currentUser.uid}`),vote);
}
window.showJokeVoters=function(reaction){
  const option=jokeReactionOptions().find(r=>r.id===reaction),voters=jokeVotes.filter(v=>v.reaction===reaction);$('mo-content').classList.remove('module-manager-modal');$('mo-content').innerHTML=`<div class="mo-title">${option.emoji} ${option.label}（${voters.length}）</div><div class="joke-voter-list">${voters.length?voters.map(v=>`<div class="joke-voter">${escAttr(v.userName||'未命名成員')}</div>`).join(''):'<div class="empty">目前還沒有人選擇這個反應</div>'}</div><div class="mo-footer"><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';
}
window.showCustomJokeLibrary=async function(){
  if(!isSystemAdmin())return;await loadBuiltinJokes();if(!localTestMode){try{const snap=await getDocs(collection(db,'customJokes'));customJokes=snap.docs.map(d=>({id:d.id,...d.data()}));}catch(error){console.error(error);}}
  const builtins=builtinJokes.map(j=>({...j,libraryType:'builtin'})),customs=customJokes.map(j=>({...j,source:'custom',sourceRef:j.id,libraryType:'custom'})),items=[...builtins,...customs],rows=items.map(j=>`<div class="joke-library-row" data-joke-search="${escAttr([j.title,j.content,j.source==='custom'?'自建':'內建題庫'].join(' ').toLowerCase())}"><div class="joke-library-copy"><div class="joke-library-title"><span>${escAttr(j.title||'每日笑話')}</span><span class="joke-library-source ${j.libraryType==='custom'?'custom':''}">${j.libraryType==='custom'?'自建':'內建'}</span></div><div class="joke-library-content" title="${escAttr(j.content||'')}">${escAttr(j.content||'')}</div></div>${j.libraryType==='custom'?`<div class="joke-library-actions"><button class="btn btn-sm" onclick="editCustomJoke('${escAttr(j.id)}')">編輯</button><button class="btn btn-sm btn-danger" onclick="deleteCustomJoke('${escAttr(j.id)}')">刪除</button></div>`:''}</div>`).join('');
  $('mo-content').classList.remove('module-manager-modal');$('mo-content').style.maxWidth='760px';$('mo-content').innerHTML=`<div class="mo-title">每日笑話題庫</div><div class="joke-library-summary">共 ${items.length} 則：內建 ${builtins.length} 則、自建 ${customs.length} 則。每列最多顯示兩行內容。</div><div style="display:grid;gap:7px;margin-top:12px"><input id="custom-joke-title" placeholder="笑話標題（可留白）"><textarea id="custom-joke-content" rows="4" placeholder="輸入自建笑話內容"></textarea><input id="custom-joke-id" type="hidden"><div style="display:flex;justify-content:flex-end;gap:7px"><button class="btn" onclick="resetCustomJokeForm()">清除</button><button class="btn btn-p" onclick="saveCustomJoke()">儲存笑話</button></div></div><input id="joke-library-search" style="margin-top:10px" placeholder="搜尋笑話內容、類別或來源" oninput="filterJokeLibrary(this.value)"><div class="joke-library-list" id="joke-library-list">${rows||'<div class="empty">題庫尚無笑話。</div>'}</div><div class="mo-footer"><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';
}
window.filterJokeLibrary=function(value){const query=String(value||'').trim().toLowerCase();document.querySelectorAll('#joke-library-list .joke-library-row').forEach(row=>row.style.display=!query||row.dataset.jokeSearch.includes(query)?'flex':'none');}
window.resetCustomJokeForm=function(){['custom-joke-id','custom-joke-title','custom-joke-content'].forEach(id=>{const el=$(id);if(el)el.value='';});}
window.editCustomJoke=function(id){const j=customJokes.find(x=>x.id===id);if(!j)return;$('custom-joke-id').value=id;$('custom-joke-title').value=j.title||'';$('custom-joke-content').value=j.content||'';$('custom-joke-content').focus();}
window.saveCustomJoke=async function(){if(!isSystemAdmin())return;const id=$('custom-joke-id').value||`custom-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,title=$('custom-joke-title').value.trim(),content=$('custom-joke-content').value.trim();if(!content)return alert('請輸入笑話內容。');const data={title:title||'未命名笑話',content,updatedBy:currentUser.uid,updatedAt:serverTimestamp()};if(localTestMode){const old=customJokes.find(x=>x.id===id);if(old)Object.assign(old,data);else customJokes.push({id,...data});}else await setDoc(doc(db,'customJokes',id),data);showCustomJokeLibrary();}
window.deleteCustomJoke=async function(id){if(!isSystemAdmin()||!confirm('確定刪除這則自建笑話？'))return;if(localTestMode)customJokes=customJokes.filter(x=>x.id!==id);else await deleteDoc(doc(db,'customJokes',id));showCustomJokeLibrary();}
