// Runtime-composed source module. Keep declarations in shared application scope.
// ── Daily quiz ──
function quizMonthKey(day=jokeDayKey()){return day.slice(0,7);}
function quizMine(){return quizAnswers.find(a=>a.uid===currentUser?.uid);}
function quizStats(){const correct=quizAnswers.filter(a=>a.correct).length,total=quizAnswers.length;return{total,correct,wrong:total-correct,rate:total?Math.round(correct/total*100):0};}
function quizDayNumber(day){return Math.floor(Date.parse(day+'T00:00:00Z')/86400000);}
function uniqueQuizDays(rows){const days={};rows.forEach(a=>{if(!days[a.day]||a.quizId===todayQuiz?.id)days[a.day]=a;});return Object.values(days);}
function currentQuizStreak(){
  const mine=uniqueQuizDays(quizUserAnswers).sort((a,b)=>a.day.localeCompare(b.day)),last=mine.at(-1);if(!last||!last.correct)return 0;
  const todayN=quizDayNumber(jokeDayKey()),lastN=quizDayNumber(last.day);if(todayN-lastN>1)return 0;
  let streak=1;for(let i=mine.length-2;i>=0;i--){if(!mine[i].correct||quizDayNumber(mine[i+1].day)-quizDayNumber(mine[i].day)!==1)break;streak++;}return streak;
}
function quizMonthBest(){
  const byUser={};quizMonthAnswers.forEach(a=>(byUser[a.uid]||(byUser[a.uid]=[])).push(a));let best=0,names=[];
  Object.values(byUser).forEach(raw=>{const rows=uniqueQuizDays(raw).sort((a,b)=>a.day.localeCompare(b.day));let run=0,peak=0,prev=null;rows.forEach(a=>{run=a.correct&&(!prev||quizDayNumber(a.day)-quizDayNumber(prev)===1)?run+1:a.correct?1:0;peak=Math.max(peak,run);prev=a.day;});const name=rows.at(-1)?.userName||'同事';if(peak>best){best=peak;names=[name];}else if(peak&&peak===best&&!names.includes(name))names.push(name);});return{best,names};
}
function renderLegacyDailyQuizModule(){
  if(quizLoading&&!todayQuiz)return'<div class="quiz-loading">今日題目載入中…</div>';if(!todayQuiz)return'<div class="quiz-loading">今日題目準備中…</div>';
  const mine=quizMine(),stats=quizStats(),best=quizMonthBest(),letters=['A','B','C','D'];
  const options=letters.map(letter=>{let cls=quizSelected===letter?'selected':'';if(mine){if(letter===todayQuiz.answer)cls='correct';else if(letter===mine.selectedAnswer)cls='wrong';}return`<button class="quiz-option ${cls}" ${mine?'disabled':''} onclick="event.stopPropagation();selectDailyQuizAnswer('${letter}')"><strong>${letter}.</strong> ${escAttr(todayQuiz.options?.[letter]||'')}</button>`;}).join('');
  return`<div class="daily-quiz"><div class="quiz-question">${escAttr(todayQuiz.question)}</div><div class="quiz-options">${options}</div>${mine?`<div class="quiz-result"><strong class="${mine.correct?'ok':'bad'}">${mine.correct?'答對了！':'答錯了'}</strong>　正確答案：${todayQuiz.answer}<span class="quiz-result-explain">${todayQuiz.analytic?`<br>${escAttr(todayQuiz.analytic)}`:''}</span><div class="quiz-stats">今日 ${stats.total} 人作答　<button class="quiz-stat-button" onclick="event.stopPropagation();showQuizAnswerUsers(true)">答對 ${stats.correct}</button>　<button class="quiz-stat-button" onclick="event.stopPropagation();showQuizAnswerUsers(false)">答錯 ${stats.wrong}</button>　正確率 ${stats.rate}%</div></div>`:''}<div class="quiz-actions"><span class="quiz-streak">🔥 目前連勝 ${currentQuizStreak()} 天 <span class="quiz-month-best">${best.best?`・🏆 本月最高：${escAttr(best.names.join('、'))} ${best.best} 天`:''}</span></span>${!mine?`<button class="btn btn-p" ${quizSelected?'':'disabled'} onclick="event.stopPropagation();submitDailyQuizAnswer()">送出答案</button>`:''}${isSystemAdmin()?'<button class="btn" onclick="event.stopPropagation();replaceTodayQuiz()">換一題</button>':''}</div></div>`;
}
function localQuizPick(){const pool=LOCAL_QUIZ_FALLBACKS.filter(q=>q.question!==todayQuiz?.question),pick=(pool.length?pool:LOCAL_QUIZ_FALLBACKS)[Math.floor(Math.random()*(pool.length||LOCAL_QUIZ_FALLBACKS.length))];return{...pick,type:'multiple-choice',source:'local-fallback'};}
async function fetchTianQuiz(){const response=await fetch('/api/quiz',{headers:{accept:'application/json'}});if(!response.ok)throw new Error(`quiz api ${response.status}`);const data=await response.json();if(!data?.question||!data?.answer)throw new Error('quiz api empty');return data;}
async function chooseNewQuiz(){if(localTestMode)return localQuizPick();try{return await fetchTianQuiz();}catch(error){console.warn('TianAPI quiz unavailable, using fallback',error);return localQuizPick();}}
function makeLegacyQuizRecord(item,reason){const day=jokeDayKey();return{id:`quiz-${day}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,day,month:quizMonthKey(day),type:item.type||'multiple-choice',question:item.question,options:item.options,answer:item.answer,analytic:item.analytic||'',source:item.source||'fallback',sourceRef:item.sourceRef||'',reason,createdBy:currentUser?.uid||'',createdAt:serverTimestamp()};}
async function ensureLegacyTodayQuiz(){
  if(quizLoading||todayQuiz)return;quizLoading=true;if(activePanel==='home')renderHome();try{const day=jokeDayKey();if(localTestMode){todayQuiz={...makeLegacyQuizRecord(localQuizPick(),'daily'),createdAt:new Date().toISOString()};quizAnswers=[];quizMonthAnswers=[];quizUserAnswers=[];return;}const dailyRef=doc(db,'dailyQuizzes',day),existing=await getDoc(dailyRef);if(existing.exists())return;const record=makeLegacyQuizRecord(await chooseNewQuiz(),'daily');await fbRunTransaction(db,async tx=>{const latest=await tx.get(dailyRef);if(latest.exists())return;tx.set(doc(db,'quizzes',record.id),record);tx.set(dailyRef,{day,currentQuizId:record.id,updatedAt:serverTimestamp(),reason:'daily'});});}catch(error){console.error('daily quiz creation failed',error);}finally{quizLoading=false;if(activePanel==='home')renderHome();}
}
function subscribeQuizRecord(quizId){if(quizDocUnsub)quizDocUnsub();if(quizAnswersUnsub)quizAnswersUnsub();todayQuiz=null;quizAnswers=[];quizSelected='';if(!quizId){ensureTodayQuiz();return;}quizDocUnsub=onSnapshot(doc(db,'quizzes',quizId),snap=>{todayQuiz=snap.exists()?{id:snap.id,...snap.data()}:null;if(activePanel==='home')renderHome();});quizAnswersUnsub=onSnapshot(query(collection(db,'quizAnswers'),where('quizId','==',quizId)),snap=>{quizAnswers=snap.docs.map(d=>({id:d.id,...d.data()}));if(activePanel==='home')renderHome();});}
function initDailyQuiz(){if(localTestMode){if(!todayQuiz)ensureTodayQuiz();return;}const day=jokeDayKey();if(quizDailyUnsub)quizDailyUnsub();quizDailyUnsub=onSnapshot(doc(db,'dailyQuizzes',day),snap=>snap.exists()?subscribeQuizRecord(snap.data().currentQuizId):ensureTodayQuiz(),error=>console.error('daily quiz listener failed',error));if(quizMonthUnsub)quizMonthUnsub();quizMonthUnsub=onSnapshot(query(collection(db,'quizAnswers'),where('month','==',quizMonthKey(day))),snap=>{quizMonthAnswers=snap.docs.map(d=>({id:d.id,...d.data()}));if(activePanel==='home')renderHome();});if(quizUserUnsub)quizUserUnsub();quizUserUnsub=onSnapshot(query(collection(db,'quizAnswers'),where('uid','==',currentUser.uid)),snap=>{quizUserAnswers=snap.docs.map(d=>({id:d.id,...d.data()}));if(activePanel==='home')renderHome();});}
window.selectDailyQuizAnswer=function(letter){if(quizMine())return;quizSelected=letter;renderHome();}
window.submitDailyQuizAnswer=async function(){
  if(!currentUser||!todayQuiz||!quizSelected||quizMine())return;const answer={quizId:todayQuiz.id,day:todayQuiz.day,month:todayQuiz.month||quizMonthKey(),uid:currentUser.uid,userName:currentUser.displayName||currentUser.email||'同事',selectedAnswer:quizSelected,correct:quizSelected===todayQuiz.answer,answeredAt:serverTimestamp()};if(localTestMode){quizAnswers=[{...answer,id:`${todayQuiz.id}_${currentUser.uid}`}];quizMonthAnswers=[...quizMonthAnswers.filter(a=>!(a.quizId===todayQuiz.id&&a.uid===currentUser.uid)),quizAnswers[0]];quizUserAnswers=[...quizUserAnswers.filter(a=>a.day!==answer.day),quizAnswers[0]];renderHome();return;}const ref=doc(db,'quizAnswers',`${todayQuiz.id}_${currentUser.uid}`);await fbRunTransaction(db,async tx=>{const existing=await tx.get(ref);if(!existing.exists())tx.set(ref,answer);});
}
window.replaceTodayQuiz=async function(){if(!isSystemAdmin()||quizLoading)return;quizLoading=true;if(activePanel==='home')renderHome();try{const record=makeQuizRecord(await chooseNewQuiz(),'manual');if(localTestMode){todayQuiz={...record,createdAt:new Date().toISOString()};quizAnswers=[];quizSelected='';}else{await setDoc(doc(db,'quizzes',record.id),record);await setDoc(doc(db,'dailyQuizzes',jokeDayKey()),{day:jokeDayKey(),currentQuizId:record.id,updatedAt:serverTimestamp(),reason:'manual',changedBy:currentUser.uid});}}catch(error){console.error(error);alert('目前無法更換題目，請稍後再試。');}finally{quizLoading=false;if(activePanel==='home')renderHome();}}
window.showQuizAnswerUsers=function(correct){if(!quizMine())return;const rows=quizAnswers.filter(a=>a.correct===correct);$('mo-content').classList.remove('module-manager-modal');$('mo-content').innerHTML=`<div class="mo-title">${correct?'答對':'答錯'}（${rows.length}）</div><div class="joke-voter-list">${rows.length?rows.map(a=>`<div class="joke-voter">${escAttr(a.userName||'同事')}</div>`).join(''):'<div class="empty">目前沒有人</div>'}</div><div class="mo-footer"><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
