// Runtime-composed source module. Keep declarations in shared application scope.
// ── Planned growth list ──
let growthManagerTab='active';
function growthProjectIds(item){return [...new Set((Array.isArray(item?.projectIds)?item.projectIds:[]).map(String).filter(Boolean))];}
function growthCount(item){return growthProjectIds(item).length;}
function growthIsComplete(item){return growthCount(item)>=3;}
function growthStamp(){return localTestMode?new Date().toISOString():serverTimestamp();}
function growthDate(value){if(!value)return'';const date=value?.toDate?value.toDate():new Date(value);return Number.isNaN(date.getTime())?'':date.toLocaleDateString('zh-TW');}
function growthProjectName(id){return S.projects.find(p=>String(p.id)===String(id))?.name||'已刪除的案件';}
function growthSafeUrl(value){let url=String(value||'').trim();if(!url)return'';if(!/^https?:\/\//i.test(url))url='https://'+url;try{const parsed=new URL(url);return ['http:','https:'].includes(parsed.protocol)?parsed.href:'';}catch{return'';}}
function growthUrls(item){return[item?.url,item?.url2].map(growthSafeUrl).filter(Boolean);}
function sortedGrowthItems(){return S.growthItems.slice().sort((a,b)=>growthIsComplete(a)-growthIsComplete(b)||(growthDate(b.createdAt)||'').localeCompare(growthDate(a.createdAt)||''));}
function growthRow(item,manage=false){const ids=growthProjectIds(item),count=Math.min(ids.length,3),urls=growthUrls(item),url=urls[0]||'',completed=growthIsComplete(item);if(!manage)return`<div class="growth-row"><${url?'button':'span'} class="growth-name${url?' link':''}" ${url?`onclick="openGrowthUrl('${escAttr(item.id)}',0)"`:''}>${escAttr(item.name||'未命名項目')}</${url?'button':'span'}><span class="growth-links">${urls.map((link,index)=>`<button class="growth-link" title="開啟參考連結 ${index+1}" aria-label="開啟 ${escAttr(item.name)} 的參考連結 ${index+1}" onclick="openGrowthUrl('${escAttr(item.id)}',${index})">${index+1}↗</button>`).join('')}</span><span class="growth-progress">${count} / 3</span><button class="growth-use" onclick="showGrowthUseForm('${escAttr(item.id)}')">＋使用</button></div>`;
  return`<div class="growth-manage-row"><div class="growth-manage-title">${url?`<button class="growth-name link" onclick="openGrowthUrl('${escAttr(item.id)}')">${escAttr(item.name)}</button>`:escAttr(item.name)}</div><div class="growth-manage-progress"><strong class="${completed?'growth-complete':''}">${count} / 3${completed?'　已完成':''}</strong>${completed&&item.completedAt?`<br>完成 ${escAttr(growthDate(item.completedAt))}`:''}</div><div class="growth-project-list">${ids.length?ids.map(projectId=>`<span class="growth-project-chip">${escAttr(growthProjectName(projectId))}<button title="刪除此使用紀錄" onclick="removeGrowthUsage('${escAttr(item.id)}','${escAttr(projectId)}')">×</button></span>`).join(''):'<span class="growth-project-empty">尚未使用案件</span>'}</div><div class="growth-manage-actions">${!completed?`<button class="btn btn-sm btn-p" onclick="showGrowthUseForm('${escAttr(item.id)}')">＋使用</button>`:''}<button class="btn btn-sm" onclick="showGrowthForm('${escAttr(item.id)}')">編輯</button><button class="btn btn-sm btn-r" onclick="deleteGrowthItem('${escAttr(item.id)}')">刪除</button></div></div>`;
}
function renderGrowthModule(){const items=sortedGrowthItems().filter(item=>!growthIsComplete(item));return`<div class="growth-preview"><div class="growth-list">${items.length?items.map(item=>growthRow(item)).join(''):'<div class="empty">目前沒有進行中的成長項目</div>'}</div><div class="growth-preview-actions"><button onclick="showGrowthForm()">＋ 新增成長項目</button><button onclick="showAllGrowthItems()">查看全部 →</button></div></div>`;}
window.openGrowthUrl=function(id,index=0){const item=S.growthItems.find(x=>x.id===id),url=growthUrls(item)[Number(index)||0];if(url)window.open(url,'_blank','noopener,noreferrer');}
window.showGrowthForm=function(id){const item=id?S.growthItems.find(x=>x.id===id):null;$('mo-content').className='mo-box growth-modal';$('mo-content').innerHTML=`<div class="mo-title">${item?'編輯成長項目':'新增成長項目'}</div><div class="mo-sub">把值得嘗試的設計或施工做法先記下來。</div><div class="growth-form"><label class="growth-field"><span class="growth-field-label"><i>✦</i>項目名稱 <small>必填</small></span><span class="growth-input-wrap"><input id="growth-name" maxlength="100" placeholder="例如：客製框明鏡" value="${escAttr(item?.name||'')}"></span></label><label class="growth-field"><span class="growth-field-label"><i>1↗</i>參考連結 1 <small>選填</small></span><span class="growth-input-wrap"><input id="growth-url" type="url" maxlength="1000" placeholder="貼上主要參考網址" value="${escAttr(item?.url||'')}"></span></label><label class="growth-field"><span class="growth-field-label"><i>2↗</i>參考連結 2 <small>選填</small></span><span class="growth-input-wrap"><input id="growth-url-2" type="url" maxlength="1000" placeholder="需要時再貼第二個參考網址" value="${escAttr(item?.url2||'')}"></span><span class="growth-field-hint">兩個連結會在首頁顯示為 1↗、2↗，可分別直接開啟。</span></label></div><div class="mo-footer"><button class="btn" onclick="${item?'showAllGrowthItems()':'closeMo()'}">取消</button><button class="btn btn-p" onclick="saveGrowthItem('${escAttr(id||'')}')">儲存</button></div>`;$('modal').style.display='flex';setTimeout(()=>$('growth-name')?.focus(),0);}
window.saveGrowthItem=async function(id){const name=$('growth-name').value.trim(),rawUrl=$('growth-url').value.trim(),rawUrl2=$('growth-url-2').value.trim();if(!name)return alert('請輸入項目名稱。');if(rawUrl&&!growthSafeUrl(rawUrl))return alert('參考連結 1 格式不正確。');if(rawUrl2&&!growthSafeUrl(rawUrl2))return alert('參考連結 2 格式不正確。');const old=id?S.growthItems.find(x=>x.id===id):null,stamp=growthStamp(),data={name,url:rawUrl,url2:rawUrl2,updatedBy:currentUser.uid,updatedAt:stamp};if(old){await updateDoc(doc(db,'growthItems',id),data);if(!localTestMode)Object.assign(old,data);}else{const created={...data,projectIds:[],createdBy:currentUser.uid,createdAt:stamp,completedAt:null};await addDoc(collection(db,'growthItems'),created);}if(localTestMode){closeMo();renderHome();}else{showAllGrowthItems();renderHome();}}
window.showGrowthUseForm=function(id){const item=S.growthItems.find(x=>x.id===id);if(!item)return;const used=new Set(growthProjectIds(item)),projects=S.projects.filter(p=>!used.has(String(p.id))).sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'zh-TW'));$('mo-content').className='mo-box growth-modal';$('mo-content').innerHTML=`<div class="mo-title">新增使用紀錄</div><div class="mo-sub">${escAttr(item.name)}　目前 ${Math.min(used.size,3)} / 3</div><div class="growth-form"><select id="growth-project"><option value="">請選擇案件／工地</option>${projects.map(p=>`<option value="${escAttr(p.id)}">${escAttr(p.name)}</option>`).join('')}</select></div>${projects.length?'':'<div class="empty">目前沒有其他可選擇的案件</div>'}<div class="mo-footer"><button class="btn" onclick="closeMo()">取消</button><button class="btn btn-p" ${projects.length?'':'disabled'} onclick="addGrowthUsage('${escAttr(id)}')">確認使用</button></div>`;$('modal').style.display='flex';}
window.addGrowthUsage=async function(id){const item=S.growthItems.find(x=>x.id===id),projectId=$('growth-project')?.value;if(!item||!projectId)return alert('請選擇案件／工地。');const ids=growthProjectIds(item);if(ids.includes(projectId))return alert('同一個案件只能計算一次。');ids.push(projectId);const patch={projectIds:ids,completedAt:ids.length>=3?(item.completedAt||growthStamp()):null,updatedBy:currentUser.uid,updatedAt:growthStamp()};await updateDoc(doc(db,'growthItems',id),patch);if(!localTestMode)Object.assign(item,patch);closeMo();renderHome();}
window.removeGrowthUsage=async function(id,projectId){const item=S.growthItems.find(x=>x.id===id);if(!item||!confirm(`確定刪除「${growthProjectName(projectId)}」的使用紀錄？`))return;const ids=growthProjectIds(item).filter(x=>x!==projectId),patch={projectIds:ids,completedAt:ids.length>=3?item.completedAt:null,updatedBy:currentUser.uid,updatedAt:growthStamp()};await updateDoc(doc(db,'growthItems',id),patch);if(!localTestMode)Object.assign(item,patch);showAllGrowthItems();renderHome();}
window.deleteGrowthItem=async function(id){const item=S.growthItems.find(x=>x.id===id);if(!item||!confirm(`確定刪除成長項目「${item.name}」？`))return;await deleteDoc(doc(db,'growthItems',id));if(!localTestMode)S.growthItems=S.growthItems.filter(x=>x.id!==id);showAllGrowthItems();renderHome();}
window.setGrowthManagerTab=function(tab){growthManagerTab=tab==='complete'?'complete':'active';showAllGrowthItems();}
window.showAllGrowthItems=function(){const completed=growthManagerTab==='complete',items=sortedGrowthItems().filter(item=>growthIsComplete(item)===completed);$('mo-content').className='mo-box growth-modal';$('mo-content').innerHTML=`<div class="mo-title">計畫性成長清單</div><div class="growth-tabs"><button class="growth-tab ${!completed?'active':''}" onclick="setGrowthManagerTab('active')">進行中</button><button class="growth-tab ${completed?'active':''}" onclick="setGrowthManagerTab('complete')">已完成</button></div><div class="growth-manage-list">${items.length?items.map(item=>growthRow(item,true)).join(''):`<div class="empty">目前沒有${completed?'已完成':'進行中'}項目</div>`}</div><div class="mo-footer"><button class="btn btn-p" onclick="showGrowthForm()">＋ 新增成長項目</button><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
