// Runtime-composed source module. Keep declarations in shared application scope.
// ── Shared sticky-note wall ──
const HOME_NOTE_LIMIT=100;
const HOME_NOTE_BLOCKED_TERMS=['政治','政黨','選舉','宗教','色情','歧視','霸凌','血腥'];
const HOME_NOTE_DEFAULT_BG='#fff2a8';
const HOME_NOTE_DEFAULT_TEXT='#202124';
let homeNoteDraftBg=HOME_NOTE_DEFAULT_BG,homeNoteDraftText=HOME_NOTE_DEFAULT_TEXT;
function homeNoteMember(uid){return S.members.find(m=>String(m.uid||m.id)===String(uid));}
function activeHomeNotes(){return S.homeNotes.filter(note=>note.status!=='disabled'&&note.status!=='removed'&&note.text&&homeNoteMember(note.uid)?.status!=='resigned');}
function homeStickyCards(){return stableHomeMembers().map(member=>{const uid=String(member.uid||member.id),note=activeHomeNotes().find(item=>String(item.uid)===uid)||null;return{uid,member,note};});}
function homeNoteMillis(value){if(!value)return 0;if(typeof value?.toMillis==='function')return value.toMillis();if(value?.seconds)return value.seconds*1000;const parsed=new Date(value).getTime();return Number.isFinite(parsed)?parsed:0;}
function homeNoteTime(value){const ms=homeNoteMillis(value);if(!ms)return'剛剛更新';return new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(ms));}
function renderStickyNote(card,adminTools=false){const {uid,member,note}=card,name=memberDisplayName(member),photo=member?.photoURL||'',fallback=escAttr(name.slice(0,1)),mine=uid===String(currentUser?.uid||''),bg=note?.backgroundColor||note?.color||HOME_NOTE_DEFAULT_BG,textColor=note?.textColor||HOME_NOTE_DEFAULT_TEXT,click=mine?' onclick="event.stopPropagation();openStickyWall()" title="編輯我的便條"':'';return`<article class="sticky-note ${mine?'own-note':''}" style="background:${escAttr(bg)};--sticky-text:${escAttr(textColor)}"${click}>${adminTools&&isSystemAdmin()&&note&&!mine?`<button class="sticky-note-admin" onclick="event.stopPropagation();disableHomeNote('${escAttr(uid)}')">停用</button>`:''}<div class="sticky-note-head">${photo?`<img class="sticky-note-avatar" src="${escAttr(photo)}" onerror="this.outerHTML='<span class=&quot;sticky-note-avatar sticky-note-avatar-fallback&quot;>${fallback}</span>'">`:`<span class="sticky-note-avatar sticky-note-avatar-fallback">${fallback}</span>`}<span class="sticky-note-name">${escAttr(name)}</span></div><div class="sticky-note-text">${escAttr(note?.text||'')}</div>${note?`<div class="sticky-note-time">更新於 ${homeNoteTime(note.updatedAt)}</div>`:''}</article>`;}
function renderStickyWallModule(){const cards=homeStickyCards(),mine=cards.find(card=>card.uid===String(currentUser?.uid||''))?.note;return`<div class="sticky-wall"><div class="sticky-wall-preview">${cards.map(card=>renderStickyNote(card)).join('')}</div><div class="sticky-wall-actions"><button class="btn" onclick="event.stopPropagation();openStickyWall()">${mine?'編輯我的便條':'留一張便條'}</button></div></div>`;}
function homeNoteColorButton(kind,color){const isText=kind==='text',label=isText?'文字顏色':'便條底色',icon=isText?'<span class="meeting-text-color-glyph">A</span>':'<svg class="meeting-fill-color-glyph" viewBox="0 0 24 24" aria-hidden="true"><path d="M6.2 3.4 17.7 14.9l-6.8 6.8a2 2 0 0 1-2.8 0l-5.8-5.8a2 2 0 0 1 0-2.8l7-7-3.1-3.1 1.4-1.4 3.1 3.1 1.5-1.5 1.4 1.4-7.4 7.4 5.8 5.8 2.9-2.9L4.8 4.8 6.2 3.4Z"/><path d="M18.4 17.2s-2.5 2.8-2.5 4.3a2.5 2.5 0 0 0 5 0c0-1.5-2.5-4.3-2.5-4.3Z"/></svg>';return`<button type="button" class="meeting-color-button" aria-label="${label}" title="${label}" onclick="openHomeNoteColorPalette(event,'${kind}')"><span class="meeting-color-icon">${icon}</span><span class="meeting-color-bar" id="home-note-${kind}-bar" style="background:${color}"></span></button>`;}
window.openStickyWall=function(){const cards=homeStickyCards(),mine=S.homeNotes.find(note=>note.uid===currentUser?.uid&&note.status!=='removed'&&note.status!=='disabled'&&note.text);homeNoteDraftBg=mine?.backgroundColor||mine?.color||HOME_NOTE_DEFAULT_BG;homeNoteDraftText=mine?.textColor||HOME_NOTE_DEFAULT_TEXT;$('mo-content').className='mo-box sticky-wall-modal';$('mo-content').innerHTML=`<div class="mo-title">便條紙留言牆</div><div class="mo-sub">這裡只是一面輕鬆的公共便條牆，不作為公告、工作指派或緊急聯絡。</div><div class="sticky-wall-grid">${cards.map(card=>renderStickyNote(card,true)).join('')}</div><div class="sticky-wall-editor" id="sticky-wall-editor" style="background:${escAttr(homeNoteDraftBg)};--sticky-text:${escAttr(homeNoteDraftText)}"><div style="font-weight:600;margin-bottom:6px">${mine?'編輯我的便條':'隨便留點什麼吧～'}</div><textarea id="home-note-text" maxlength="${HOME_NOTE_LIMIT}" placeholder="一句話或一個表情符號都可以" oninput="updateHomeNoteCount()">${escAttr(mine?.text||'')}</textarea><div class="sticky-note-format meeting-color-controls" aria-label="便條紙文字與底色">${homeNoteColorButton('text',homeNoteDraftText)}${homeNoteColorButton('bg',homeNoteDraftBg)}</div><div class="sticky-wall-editor-foot"><span class="sticky-wall-count" id="home-note-count">${(mine?.text||'').length} / ${HOME_NOTE_LIMIT}</span>${mine?'<button class="btn btn-danger" onclick="removeMyHomeNote()">移除</button>':''}<button class="btn btn-p" onclick="saveMyHomeNote()">${mine?'儲存':'貼上'}</button></div></div><div class="mo-footer"><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.openHomeNoteColorPalette=function(e,kind){e.stopPropagation();closeMeetingColorPalette();const current=kind==='text'?homeNoteDraftText:homeNoteDraftBg,palette=document.createElement('div');palette.id='meeting-color-palette';palette.className='meeting-color-palette';const swatch=color=>`<button type="button" class="meeting-palette-swatch ${current.toLowerCase()===color.toLowerCase()?'selected':''}" style="background:${color}" title="${color}" aria-label="選擇 ${color}" onclick="pickHomeNoteColor('${kind}','${color}')"></button>`;palette.innerHTML=MEETING_COLOR_ROWS.map(row=>`<div class="meeting-palette-grid">${row.map(swatch).join('')}</div>`).join('')+`<div class="meeting-palette-standard">標準</div><div class="meeting-palette-grid">${MEETING_STANDARD_COLORS.map(swatch).join('')}</div><label class="meeting-palette-custom"><span>自訂</span><input type="color" value="${current}" aria-label="自訂顏色" onchange="pickHomeNoteColor('${kind}',this.value)"></label>`;document.body.appendChild(palette);const rect=e.currentTarget.getBoundingClientRect(),pr=palette.getBoundingClientRect();palette.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-pr.width-8))+'px';palette.style.top=Math.max(8,Math.min(rect.bottom+6,window.innerHeight-pr.height-8))+'px';}
window.pickHomeNoteColor=function(kind,color){if(!/^#[0-9a-f]{6}$/i.test(color))return;if(kind==='text')homeNoteDraftText=color;else homeNoteDraftBg=color;const editor=$('sticky-wall-editor'),bar=$(`home-note-${kind}-bar`);if(editor){editor.style.background=homeNoteDraftBg;editor.style.setProperty('--sticky-text',homeNoteDraftText);}if(bar)bar.style.background=color;closeMeetingColorPalette();}
window.updateHomeNoteCount=function(){const input=$('home-note-text'),count=$('home-note-count');if(input&&count)count.textContent=`${input.value.length} / ${HOME_NOTE_LIMIT}`;}
window.saveMyHomeNote=async function(){if(!currentUser)return;const text=$('home-note-text')?.value.trim()||'';if(!text)return alert('請輸入便條內容。');if(text.length>HOME_NOTE_LIMIT)return alert(`便條最多 ${HOME_NOTE_LIMIT} 個字。`);if(HOME_NOTE_BLOCKED_TERMS.some(term=>text.includes(term)))return alert('內容包含不適合公司留言牆的文字，請調整後再試。');const existing=S.homeNotes.find(note=>note.uid===currentUser.uid),stamp=localTestMode?new Date().toISOString():serverTimestamp(),data={uid:currentUser.uid,text,backgroundColor:homeNoteDraftBg,textColor:homeNoteDraftText,status:'active',updatedAt:stamp};if(!existing)data.createdAt=stamp;await setDoc(doc(db,'homeNotes',currentUser.uid),data,{merge:true});if(localTestMode)openStickyWall();}
window.removeMyHomeNote=async function(){if(!currentUser||!confirm('確定移除自己的便條紙？'))return;const stamp=localTestMode?new Date().toISOString():serverTimestamp();await setDoc(doc(db,'homeNotes',currentUser.uid),{status:'removed',removedBy:currentUser.uid,removedAt:stamp,updatedAt:stamp},{merge:true});if(localTestMode)openStickyWall();}
window.disableHomeNote=async function(uid){if(!isSystemAdmin()||!confirm('確定停用這張不適當的便條紙？原始內容與管理紀錄會保留。'))return;const stamp=localTestMode?new Date().toISOString():serverTimestamp();await setDoc(doc(db,'homeNotes',uid),{status:'disabled',disabledBy:currentUser.uid,disabledAt:stamp,updatedAt:stamp},{merge:true});if(localTestMode)openStickyWall();}
