// Runtime-composed source module. Keep declarations in shared application scope.
// ── Shared quiz bank ──
function quizShuffle(ids){const out=ids.slice();for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
function nextLocalQuizBankItem(){const ids=LOCAL_QUIZ_BANK.filter(q=>q.enabled).map(q=>q.id);if(!ids.length)throw new Error('題庫沒有啟用中的題目');if(localQuizRotation.cursor>=localQuizRotation.order.length||!localQuizRotation.order.length){let order=quizShuffle(ids);if(ids.length>1&&order[0]===localQuizRotation.lastQuizId)[order[0],order[1]]=[order[1],order[0]];localQuizRotation={order,cursor:0,lastQuizId:localQuizRotation.lastQuizId,round:localQuizRotation.round+1};}const id=localQuizRotation.order[localQuizRotation.cursor++];localQuizRotation.lastQuizId=id;return LOCAL_QUIZ_BANK.find(q=>q.id===id);}
function makeQuizBankRecord(item,reason){const day=jokeDayKey();return{id:`quiz-${day}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,day,month:quizMonthKey(day),type:'multiple-choice',question:item.question,options:item.options,answer:item.answer,analytic:item.analytic||'',category:item.category||'',difficulty:item.difficulty||'',source:item.source||'quizBank',sourceRef:item.sourceId||item.id||'',bankQuizId:item.id||'',reason,createdBy:currentUser?.uid||'',createdAt:serverTimestamp()};}
async function createQuizFromBank(reason,replaceCurrent=false){
  const day=jokeDayKey(),dailyRef=doc(db,'dailyQuizzes',day);
  if(localTestMode){const item=nextLocalQuizBankItem();todayQuiz={...makeQuizBankRecord(item,reason),createdAt:new Date().toISOString()};quizAnswers=[];quizSelected='';return;}
  if(!replaceCurrent){const existing=await getDoc(dailyRef);if(existing.exists())return;}
  const bankSnap=await getDocs(query(collection(db,'quizBank'),where('enabled','==',true))),candidates=bankSnap.docs.map(s=>({id:s.id,...s.data()}));if(!candidates.length)throw new Error('尚未匯入啟用中的題庫');
  const rotationRef=doc(db,'settings','quizRotation');await fbRunTransaction(db,async tx=>{if(!replaceCurrent){const latest=await tx.get(dailyRef);if(latest.exists())return;}const rotationSnap=await tx.get(rotationRef);let rotation=rotationSnap.exists()?rotationSnap.data():{},order=Array.isArray(rotation.order)?rotation.order.filter(id=>candidates.some(q=>q.id===id)):[],cursor=Number(rotation.cursor)||0,lastQuizId=rotation.lastQuizId||'',round=Number(rotation.round)||0;if(cursor>=order.length||!order.length){order=quizShuffle(candidates.map(q=>q.id));if(order.length>1&&order[0]===lastQuizId)[order[0],order[1]]=[order[1],order[0]];cursor=0;round++;}const bankQuizId=order[cursor++],item=candidates.find(q=>q.id===bankQuizId),record=makeQuizBankRecord(item,reason);tx.set(doc(db,'quizzes',record.id),record);tx.set(dailyRef,{day,currentQuizId:record.id,updatedAt:serverTimestamp(),reason});tx.set(rotationRef,{order,cursor,lastQuizId:bankQuizId,round,updatedAt:serverTimestamp()});});
}
async function ensureTodayQuiz(){if(quizLoading||todayQuiz)return;quizLoading=true;if(activePanel==='home')renderHome();try{await createQuizFromBank('daily');}catch(error){console.error('daily quiz creation failed',error);if(activePanel==='home')alert('每日猜題尚未建立題庫。');}finally{quizLoading=false;if(activePanel==='home')renderHome();}}
window.replaceTodayQuiz=async function(){if(!isSystemAdmin()||quizLoading)return;quizLoading=true;if(activePanel==='home')renderHome();try{await createQuizFromBank('manual',true);}catch(error){console.error(error);alert(error.message||'目前無法更換題目，請稍後再試。');}finally{quizLoading=false;if(activePanel==='home')renderHome();}}
function renderDailyQuizModule(){if(quizLoading&&!todayQuiz)return'<div class="quiz-loading">今日題目載入中…</div>';if(!todayQuiz)return'<div class="quiz-loading">今日題目準備中…</div>';const mine=quizMine(),stats=quizStats(),best=quizMonthBest(),letters=['A','B','C','D'],options=letters.map(letter=>{let cls=quizSelected===letter?'selected':'';if(mine){if(letter===todayQuiz.answer)cls='correct';else if(letter===mine.selectedAnswer)cls='wrong';}return`<button class="quiz-option ${cls}" ${mine?'disabled':''} onclick="event.stopPropagation();selectDailyQuizAnswer('${letter}')"><strong>${letter}.</strong> ${escAttr(todayQuiz.options?.[letter]||'')}</button>`;}).join('');return`<div class="daily-quiz"><div class="quiz-question">${escAttr(todayQuiz.question)}</div><div class="quiz-options">${options}</div>${mine?`<div class="quiz-result"><strong class="${mine.correct?'ok':'bad'}">${mine.correct?'答對了！':'答錯了'}</strong>　正確答案：${todayQuiz.answer}${todayQuiz.analytic?`<br>${escAttr(todayQuiz.analytic)}`:''}<div class="quiz-stats">今日 ${stats.total} 人作答　<button class="quiz-stat-button" onclick="event.stopPropagation();showQuizAnswerUsers(true)">答對 ${stats.correct}</button>　<button class="quiz-stat-button" onclick="event.stopPropagation();showQuizAnswerUsers(false)">答錯 ${stats.wrong}</button>　正確率 ${stats.rate}%</div></div>`:''}<div class="quiz-actions"><span class="quiz-streak">🔥 目前連勝 ${currentQuizStreak()} 天 <span class="quiz-month-best">${best.best?`・🏆 本月最高：${escAttr(best.names.join('、'))} ${best.best} 天`:''}</span></span>${!mine?`<button class="btn btn-p" ${quizSelected?'':'disabled'} onclick="event.stopPropagation();submitDailyQuizAnswer()">送出答案</button>`:''}${isSystemAdmin()?'<button class="btn" onclick="event.stopPropagation();showQuizBank()">題庫</button><button class="btn" onclick="event.stopPropagation();replaceTodayQuiz()">換一題</button>':''}</div></div>`;}
let quizBankViewFilters={query:'',difficulty:'',category:''};
function quizDifficultyLabel(value){return({easy:'Easy',medium:'Normal',hard:'Hard'})[value]||'未設定';}
function renderQuizBankModal(items){const enabled=items.filter(item=>item.enabled!==false).length,categories=[...new Set(items.map(item=>String(item.category||'未分類').trim()||'未分類'))].sort((a,b)=>a.localeCompare(b,'zh-Hant')),counts={easy:0,medium:0,hard:0};items.forEach(item=>{if(counts[item.difficulty]!==undefined)counts[item.difficulty]++;});const rows=items.slice().sort((a,b)=>String(a.question||'').localeCompare(String(b.question||''),'zh-Hant')).map(item=>{const options=['A','B','C','D'].map(letter=>`${letter}. ${item.options?.[letter]||''}`).join('　'),category=String(item.category||'未分類').trim()||'未分類',difficulty=item.difficulty||'';return`<div class="quiz-bank-row" data-quiz-search="${escAttr([item.question,options,category,difficulty,item.source].join(' ').toLowerCase())}" data-quiz-difficulty="${escAttr(difficulty)}" data-quiz-category="${escAttr(category)}"><strong>${escAttr(item.question||'未命名題目')}</strong><div>${escAttr(options)}</div><small>答案：${escAttr(item.answer||'')}　・　${escAttr(category)}　・　${quizDifficultyLabel(difficulty)}　・　${escAttr(item.source||'自建題庫')}${item.enabled===false?'　・　已停用':''}</small></div>`;}).join('');quizBankViewFilters={query:'',difficulty:'',category:''};$('mo-content').classList.remove('module-manager-modal');$('mo-content').style.maxWidth='860px';$('mo-content').innerHTML=`<div class="mo-title">每日猜題題庫</div><div class="mo-sub">目前共 ${items.length} 題，啟用中 ${enabled} 題。每日輪播只會使用啟用中的題目。</div><div class="quiz-bank-filters"><input id="quiz-bank-search" placeholder="搜尋題目、選項、分類、難度或來源" oninput="filterQuizBank(this.value)"><select id="quiz-bank-difficulty" onchange="setQuizBankFilter('difficulty',this.value)"><option value="">所有難度（${items.length}）</option><option value="easy">Easy（${counts.easy}）</option><option value="medium">Normal（${counts.medium}）</option><option value="hard">Hard（${counts.hard}）</option></select><select id="quiz-bank-category" onchange="setQuizBankFilter('category',this.value)"><option value="">所有類別（${categories.length}）</option>${categories.map(category=>`<option value="${escAttr(category)}">${escAttr(category)}（${items.filter(item=>(String(item.category||'未分類').trim()||'未分類')===category).length}）</option>`).join('')}</select></div><div class="quiz-bank-list" id="quiz-bank-list">${rows||'<div class="empty">題庫尚未匯入題目。</div>'}</div><div class="mo-footer"><label class="btn btn-p" style="cursor:pointer">匯入 JSON<input type="file" accept="application/json,.json" hidden onchange="importQuizBankFile(this.files[0]);this.value=''"></label><button class="btn" onclick="importQuizBankBatch()">匯入下一批</button><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.showQuizBank=async function(){if(!isSystemAdmin())return;$('mo-content').classList.remove('module-manager-modal');$('mo-content').innerHTML='<div class="mo-title">每日猜題題庫</div><div class="empty">題庫載入中…</div>';$('modal').style.display='flex';try{const items=localTestMode?LOCAL_QUIZ_BANK.map(item=>({...item})):(await getDocs(collection(db,'quizBank'))).docs.map(s=>({id:s.id,...s.data()}));renderQuizBankModal(items);}catch(error){console.error('quiz bank load failed',error);$('mo-content').innerHTML='<div class="mo-title">每日猜題題庫</div><div class="empty">題庫載入失敗，請稍後再試。</div>';}}
function applyQuizBankFilters(){const filters=quizBankViewFilters;document.querySelectorAll('#quiz-bank-list .quiz-bank-row').forEach(row=>{const matched=(!filters.query||row.dataset.quizSearch.includes(filters.query))&&(!filters.difficulty||row.dataset.quizDifficulty===filters.difficulty)&&(!filters.category||row.dataset.quizCategory===filters.category);row.style.display=matched?'block':'none';});}
window.filterQuizBank=function(value){quizBankViewFilters.query=String(value||'').trim().toLowerCase();applyQuizBankFilters();};window.setQuizBankFilter=function(key,value){quizBankViewFilters[key]=String(value||'');applyQuizBankFilters();};
window.importQuizBankFile=async function(file){if(!isSystemAdmin()||!file)return;let items;try{items=JSON.parse(await file.text());}catch{return alert('JSON 檔案格式無法讀取。');}if(!Array.isArray(items)||!items.length)return alert('JSON 題庫必須是非空白陣列。');if(localTestMode)return alert(`本機已成功讀取 ${items.length} 題；測試模式不會寫入正式 Firebase。`);const button=$('mo-content').querySelector('label.btn-p');if(button){button.style.pointerEvents='none';button.style.opacity='.6';button.childNodes[0].textContent='匯入中…';}try{const token=await currentUser.getIdToken(),response=await fetch('/api/quiz-bank-import',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({items})}),result=await response.json();if(!response.ok)throw new Error(result.message||'匯入失敗');alert(`JSON 匯入完成：新增 ${result.added||0} 題，略過重複 ${result.skipped||0} 題；目前題庫共 ${result.total||0} 題。`);await showQuizBank();}catch(error){console.error('quiz bank JSON import failed',error);alert(error.message||'JSON 題庫匯入失敗，請稍後再試。');if(button){button.style.pointerEvents='';button.style.opacity='';button.childNodes[0].textContent='匯入 JSON';}}}
window.importQuizBankBatch=async function(){if(!isSystemAdmin())return;if(localTestMode)return alert('本機測試版不會呼叫外部題庫或翻譯服務。正式版部署後，只有管理員按下這個按鈕才會開始匯入。');if(!currentUser)return;const button=document.activeElement?.matches?.('button')?document.activeElement:null;if(button){button.disabled=true;button.textContent='匯入中…';}try{const token=await currentUser.getIdToken(),response=await fetch('/api/quiz-bank-import',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({batchSize:10})}),result=await response.json();if(!response.ok)throw new Error(result.message||'匯入失敗');alert(`本批新增 ${result.added||0} 題；目前題庫共 ${result.total||0} 題。`);await showQuizBank();}catch(error){console.error('quiz bank import failed',error);alert(error.message||'題庫匯入失敗，請稍後再試。');if(button){button.disabled=false;button.textContent='匯入下一批';}}}
