// Runtime-composed source module. Keep declarations in shared application scope.
// ── Shared recommendations ──
let recommendationRegionFilter='all',recommendationCategoryFilter='all',recommendationImageData='';
function recommendationTime(value){if(!value)return 0;if(typeof value?.toMillis==='function')return value.toMillis();if(typeof value?.seconds==='number')return value.seconds*1000;const parsed=new Date(value).getTime();return Number.isFinite(parsed)?parsed:0;}
function sortedRecommendations(){return S.recommendations.slice().sort((a,b)=>recommendationTime(b.createdAt)-recommendationTime(a.createdAt));}
function sortedRecommendationCategories(includeDisabled=true){return S.recommendationCategories.filter(c=>includeDisabled||c.enabled!==false).slice().sort((a,b)=>(Number(a.sortOrder)||0)-(Number(b.sortOrder)||0)||(a.name||'').localeCompare(b.name||'','zh-Hant'));}
function sortedRecommendationRegions(includeDisabled=true){return S.recommendationRegions.filter(r=>includeDisabled||r.enabled!==false).slice().sort((a,b)=>(Number(a.sortOrder)||0)-(Number(b.sortOrder)||0)||(a.name||'').localeCompare(b.name||'','zh-Hant'));}
function recommendationRegions(){return sortedRecommendationRegions(false);}
function recommendationCategory(id){return S.recommendationCategories.find(c=>c.id===id);}
function recommendationRegion(id){return S.recommendationRegions.find(r=>r.id===id);}
function recommendationLabels(item){return{region:item.regionId?(recommendationRegion(item.regionId)?.name||'未知地區'):'尚未分類',category:item.categoryId?(recommendationCategory(item.categoryId)?.name||'未知類別'):'尚未分類'};}
function recommendationCanEdit(item){return isAdmin()||item.authorUid===currentUser?.uid;}
function safeRecommendationUrl(value){try{const url=new URL(String(value||'').trim());return ['http:','https:'].includes(url.protocol)?url.href:'';}catch{return'';}}
function renderRecommendationTags(item){const labels=recommendationLabels(item);return`<div class="recommend-tags"><span class="recommend-tag region">${escAttr(labels.region)}</span><span class="recommend-tag category">${escAttr(labels.category)}</span></div>`;}
function renderRecommendationHomeTags(item){const region=item.regionId?recommendationRegion(item.regionId):null,category=item.categoryId?recommendationCategory(item.categoryId):null;return`<span class="recommend-preview-tags">${region?`<span class="recommend-tag region">${escAttr(region.name)}</span>`:''}${category?`<span class="recommend-tag category">${escAttr(category.name)}</span>`:''}</span>`;}
function renderRecommendationModule(){const items=sortedRecommendations();return`<div class="recommend-preview"><div class="recommend-preview-list">${items.length?items.map(item=>`<button type="button" class="recommend-preview-row" onclick="event.stopPropagation();showRecommendationDetail('${item.id}')"><span class="recommend-preview-title">${escAttr(item.title||'未命名推薦')}</span>${renderRecommendationHomeTags(item)}</button>`).join(''):'<div class="daily-joke-empty">目前還沒有推薦</div>'}</div><div class="recommend-preview-actions"><button class="btn" onclick="event.stopPropagation();showRecommendationForm()">＋新增</button><button class="btn btn-p" onclick="event.stopPropagation();showAllRecommendations()">查看全部</button></div></div>`;}
function recommendationFilterOptions(){const regions=recommendationRegions(),categories=sortedRecommendationCategories(false);return{regions,categories};}
function filteredRecommendations(){return sortedRecommendations().filter(item=>(recommendationRegionFilter==='all'||item.regionId===recommendationRegionFilter)&&(recommendationCategoryFilter==='all'||item.categoryId===recommendationCategoryFilter));}
function renderRecommendationCard(item){const url=safeRecommendationUrl(item.url),canEdit=recommendationCanEdit(item);return`<article class="recommend-card">${item.imageUrl?`<img class="recommend-image" src="${escAttr(item.imageUrl)}" alt="${escAttr(item.title||'推薦圖片')}">`:'<div class="recommend-image empty">✦</div>'}<div class="recommend-card-body"><div class="recommend-title">${escAttr(item.title||'未命名推薦')}</div>${renderRecommendationTags(item)}<div class="recommend-description">${escAttr(item.description||'')}</div><div class="recommend-meta">分享者：${escAttr(item.authorName||'同事')}</div><div class="recommend-card-actions">${url?`<button class="btn btn-sm" onclick="openRecommendationUrl('${escAttr(url)}')">開啟網址</button>`:''}${canEdit?`<button class="btn btn-sm" onclick="showRecommendationForm('${item.id}')">編輯</button>`:''}${isAdmin()?`<button class="btn btn-sm btn-danger" onclick="deleteRecommendation('${item.id}')">刪除</button>`:''}</div></div></article>`;}
function recommendationDateText(item){const ms=recommendationTime(item.createdAt);return ms?new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ms)):'';}
window.showRecommendationDetail=function(id){const item=S.recommendations.find(x=>x.id===id);if(!item)return;const url=safeRecommendationUrl(item.url),canEdit=recommendationCanEdit(item),dateText=recommendationDateText(item);$('mo-content').classList.remove('module-manager-modal','recommend-modal');$('mo-content').innerHTML=`<div class="mo-title">${escAttr(item.title||'未命名推薦')}</div>${renderRecommendationTags(item)}${item.imageUrl?`<img class="recommend-detail-image" src="${escAttr(item.imageUrl)}" alt="${escAttr(item.title||'推薦圖片')}">`:''}<div class="recommend-description" style="margin-top:12px">${escAttr(item.description||'')}</div><div class="recommend-meta" style="margin-top:12px">分享者：${escAttr(item.authorName||'同事')}${dateText?`　新增時間：${escAttr(dateText)}`:''}</div><div class="mo-footer">${url?`<button class="btn" onclick="openRecommendationUrl('${escAttr(url)}')">開啟網址</button>`:''}${canEdit?`<button class="btn" onclick="showRecommendationForm('${item.id}')">編輯</button>`:''}<button class="btn btn-p" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';};
window.showAllRecommendations=function(){const options=recommendationFilterOptions(),items=filteredRecommendations();$('mo-content').classList.remove('module-manager-modal');$('mo-content').classList.add('recommend-modal');$('mo-content').innerHTML=`<div class="mo-title">推薦分享</div><div class="recommend-toolbar"><select aria-label="地區篩選" onchange="setRecommendationRegionFilter(this.value)"><option value="all">全部地區</option>${options.regions.map(r=>`<option value="${r.id}" ${recommendationRegionFilter===r.id?'selected':''}>${escAttr(r.name)}</option>`).join('')}</select><select aria-label="類別篩選" onchange="setRecommendationCategoryFilter(this.value)"><option value="all">全部類別</option>${options.categories.map(c=>`<option value="${c.id}" ${recommendationCategoryFilter===c.id?'selected':''}>${escAttr(c.name)}</option>`).join('')}</select><button class="btn btn-p" onclick="showRecommendationForm()">＋新增推薦</button>${isAdmin()?'<button class="btn" onclick="showRecommendationCategoryManager()">管理設定</button>':''}</div><div class="recommend-grid">${items.length?items.map(renderRecommendationCard).join(''):'<div class="empty" style="grid-column:1/-1">沒有符合目前篩選條件的推薦</div>'}</div><div class="mo-footer"><button class="btn" onclick="closeMo()">關閉</button></div>`;$('modal').style.display='flex';}
window.setRecommendationRegionFilter=function(value){recommendationRegionFilter=value;showAllRecommendations();};
window.setRecommendationCategoryFilter=function(value){recommendationCategoryFilter=value;showAllRecommendations();};
window.openRecommendationUrl=function(value){const url=safeRecommendationUrl(value);if(url)window.open(url,'_blank','noopener');};
window.showRecommendationForm=function(id){const item=id?S.recommendations.find(x=>x.id===id):null;if(item&&!recommendationCanEdit(item))return;const activeRegions=recommendationRegions(),currentRegion=recommendationRegion(item?.regionId),regions=currentRegion&&currentRegion.enabled===false?[...activeRegions,currentRegion]:activeRegions,activeCategories=sortedRecommendationCategories(false),currentCategory=recommendationCategory(item?.categoryId),categories=currentCategory&&currentCategory.enabled===false?[...activeCategories,currentCategory]:activeCategories;recommendationImageData=item?.imageUrl||'';$('mo-content').classList.remove('module-manager-modal','recommend-modal');$('mo-content').innerHTML=`<div class="mo-title">${item?'編輯推薦':'新增推薦'}</div>${!regions.length?'<div class="mo-sub" style="color:var(--red)">目前尚無啟用中的地區，請先請管理員或主管至「管理設定」新增。</div>':''}<div class="recommend-form-grid" style="margin-top:12px"><input class="full" id="recommend-title" maxlength="80" placeholder="推薦名稱*" value="${escAttr(item?.title||'')}"><textarea class="full" id="recommend-description" rows="4" maxlength="500" placeholder="簡短介紹*">${escAttr(item?.description||'')}</textarea><select id="recommend-region"><option value="">選擇地區*</option>${regions.map(r=>`<option value="${r.id}" ${item?.regionId===r.id?'selected':''} ${r.enabled===false?'disabled':''}>${escAttr(r.name)}${r.enabled===false?'（已停用）':''}</option>`).join('')}</select><select id="recommend-category"><option value="">選擇類別*</option>${categories.map(c=>`<option value="${c.id}" ${item?.categoryId===c.id?'selected':''} ${c.enabled===false?'disabled':''}>${escAttr(c.name)}${c.enabled===false?'（已停用）':''}</option>`).join('')}</select><input class="full" id="recommend-url" inputmode="url" placeholder="網址（選填，https://…）" value="${escAttr(item?.url||'')}"><label class="full" style="font-size:12px;color:var(--text2)">圖片（選填，JPG／PNG／WebP，最大 5MB）<input id="recommend-image" type="file" accept="image/jpeg,image/png,image/webp" onchange="previewRecommendationImage(this.files[0])"></label><div class="full" id="recommend-image-wrap">${recommendationImageData?`<img class="recommend-image-preview" src="${escAttr(recommendationImageData)}" alt="圖片預覽"><button class="btn btn-sm" style="margin-top:5px" onclick="removeRecommendationImage()">移除圖片</button>`:''}</div></div><div class="mo-footer"><button class="btn" onclick="showAllRecommendations()">取消</button><button class="btn btn-p" onclick="saveRecommendation(${item?`'${item.id}'`:'null'})">儲存</button></div>`;$('modal').style.display='flex';}
window.previewRecommendationImage=async function(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){$('recommend-image').value='';return alert('請選擇 5MB 以下的 JPG、PNG 或 WebP 圖片。');}recommendationImageData=localTestMode?await fileAsDataUrl(file):'';$('recommend-image-wrap').innerHTML=localTestMode?`<img class="recommend-image-preview" src="${recommendationImageData}" alt="圖片預覽"><button class="btn btn-sm" style="margin-top:5px" onclick="removeRecommendationImage()">移除圖片</button>`:'<div style="font-size:11px;color:var(--text3)">已選擇圖片，儲存後上傳。</div>';};
window.removeRecommendationImage=function(){recommendationImageData='';const input=$('recommend-image');if(input)input.value='';$('recommend-image-wrap').innerHTML='';};
window.saveRecommendation=async function(id){const old=id?S.recommendations.find(x=>x.id===id):null;if(old&&!recommendationCanEdit(old))return;const title=$('recommend-title').value.trim(),description=$('recommend-description').value.trim(),regionId=$('recommend-region').value,categoryId=$('recommend-category').value,rawUrl=$('recommend-url').value.trim(),url=rawUrl?safeRecommendationUrl(rawUrl):'';if(!title||!description||!regionId||!categoryId)return alert('請填寫名稱、簡短介紹、地區與類別。');if(rawUrl&&!url)return alert('網址格式不正確，請輸入 http:// 或 https:// 開頭的網址。');const region=recommendationRegion(regionId),category=recommendationCategory(categoryId);if(!region||region.enabled===false)return alert('此地區目前未啟用，請改選其他地區。');if(!category||category.enabled===false)return alert('此類別目前未啟用，請改選其他類別。');let imageUrl=recommendationImageData||old?.imageUrl||'',imagePath=old?.imagePath||'';const file=$('recommend-image')?.files?.[0];try{if(file&&!localTestMode){imagePath=`recommendations/${currentUser.uid}/${Date.now()}-${safePhotoFileName(file.name)}`;const imageRef=storageRef(storage,imagePath);await uploadBytes(imageRef,file);imageUrl=await getDownloadURL(imageRef);}const stamp=localTestMode?new Date().toISOString():serverTimestamp(),data={title,description,url,imageUrl,imagePath,regionId,categoryId,authorUid:old?.authorUid||currentUser.uid,authorName:old?.authorName||currentUser.displayName||currentUser.email||'同事',updatedBy:currentUser.uid,updatedAt:stamp};if(id)await updateDoc(doc(db,'recommendations',id),data);else await addDoc(collection(db,'recommendations'),{...data,createdAt:stamp});showAllRecommendations();if(activePanel==='home')renderHome();}catch(error){console.error('recommendation save failed',error);alert('推薦暫時無法儲存，請確認連線及圖片權限後再試。');}};
window.deleteRecommendation=async function(id){if(!isAdmin())return;const item=S.recommendations.find(x=>x.id===id);if(!item||!confirm(`確定刪除「${item.title||'這則推薦'}」？`))return;await deleteDoc(doc(db,'recommendations',id));showAllRecommendations();};
function normalizeRecommendationName(value){return String(value||'').normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('zh-Hant');}
function renderRecommendationSettingRows(type,items){const field=type==='region'?'regionId':'categoryId',move=type==='region'?'moveRecommendationRegion':'moveRecommendationCategory',toggle=type==='region'?'toggleRecommendationRegion':'toggleRecommendationCategory',remove=type==='region'?'deleteRecommendationRegion':'deleteRecommendationCategory';return items.length?items.map((item,index)=>{const used=S.recommendations.filter(r=>r[field]===item.id).length;return`<div class="recommend-category-row ${item.enabled===false?'off':''}"><span>${index+1}</span><span>${escAttr(item.name)} <small style="color:var(--text3)">使用中 ${used}</small></span><button class="btn btn-sm category-secondary" ${index===0?'disabled':''} onclick="${move}('${item.id}',-1)">↑</button><button class="btn btn-sm category-secondary" ${index===items.length-1?'disabled':''} onclick="${move}('${item.id}',1)">↓</button><span style="display:flex;gap:4px"><button class="btn btn-sm" onclick="showRecommendationNameEditor('${type}','${item.id}')">編輯</button><button class="btn btn-sm" onclick="${toggle}('${item.id}')">${item.enabled===false?'啟用':'停用'}</button><button class="btn btn-sm btn-danger" ${used?'disabled':''} onclick="${remove}('${item.id}')">刪除</button></span></div>`;}).join(''):'<div class="empty">尚未新增任何項目</div>';}
window.showRecommendationCategoryManager=function(){if(!isAdmin())return;const regions=sortedRecommendationRegions(true),categories=sortedRecommendationCategories(true);$('mo-content').classList.remove('recommend-modal');$('mo-content').innerHTML=`<div class="mo-title">推薦分享管理設定</div><div class="mo-sub">地區與類別皆為全公司共用；停用後既有推薦仍保留，新建與編輯時不可再選。</div><div style="font-weight:600;margin-top:14px">地區</div><div style="display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:7px"><input id="recommend-region-name" maxlength="30" placeholder="新增地區（例如：不限地區／線上）"><button class="btn btn-p" onclick="addRecommendationRegion()">新增地區</button></div><div style="margin-top:8px">${renderRecommendationSettingRows('region',regions)}</div><div style="font-weight:600;margin-top:18px">類別</div><div style="display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:7px"><input id="recommend-category-name" maxlength="30" placeholder="新增類別名稱"><button class="btn btn-p" onclick="addRecommendationCategory()">新增類別</button></div><div style="margin-top:8px">${renderRecommendationSettingRows('category',categories)}</div><div class="mo-footer"><button class="btn" onclick="showAllRecommendations()">返回推薦</button></div>`;$('modal').style.display='flex';};
window.addRecommendationRegion=async function(){if(!isAdmin())return;const name=$('recommend-region-name').value.trim(),key=normalizeRecommendationName(name);if(!key)return alert('請輸入地區名稱。');if(S.recommendationRegions.some(r=>normalizeRecommendationName(r.name)===key))return alert('已有相同或過於相近的地區名稱。');const regions=sortedRecommendationRegions(true),stamp=localTestMode?new Date().toISOString():serverTimestamp();await addDoc(collection(db,'recommendationRegions'),{name,normalizedName:key,sortOrder:regions.length,enabled:true,createdBy:currentUser.uid,createdAt:stamp,updatedAt:stamp});showRecommendationCategoryManager();};
window.showRecommendationNameEditor=function(type,id){if(!isAdmin())return;const item=type==='region'?recommendationRegion(id):recommendationCategory(id);if(!item)return;$('mo-content').innerHTML=`<div class="mo-title">編輯${type==='region'?'地區':'類別'}名稱</div><div style="margin-top:12px"><input id="recommend-setting-edit-name" maxlength="30" value="${escAttr(item.name||'')}"></div><div class="mo-footer"><button class="btn" onclick="showRecommendationCategoryManager()">取消</button><button class="btn btn-p" onclick="saveRecommendationSettingName('${type}','${id}')">儲存</button></div>`;setTimeout(()=>$('recommend-setting-edit-name')?.focus(),50);};
window.saveRecommendationSettingName=async function(type,id){if(!isAdmin())return;const isRegion=type==='region',item=isRegion?recommendationRegion(id):recommendationCategory(id),list=isRegion?S.recommendationRegions:S.recommendationCategories,name=$('recommend-setting-edit-name').value.trim(),key=normalizeRecommendationName(name);if(!item||!key)return alert(`請輸入${isRegion?'地區':'類別'}名稱。`);if(list.some(row=>row.id!==id&&normalizeRecommendationName(row.name)===key))return alert(`已有相同或過於相近的${isRegion?'地區':'類別'}名稱。`);await updateDoc(doc(db,isRegion?'recommendationRegions':'recommendationCategories',id),{name,normalizedName:key,updatedBy:currentUser.uid,updatedAt:localTestMode?new Date().toISOString():serverTimestamp()});showRecommendationCategoryManager();};
window.toggleRecommendationRegion=async function(id){if(!isAdmin())return;const item=recommendationRegion(id);if(!item)return;await updateDoc(doc(db,'recommendationRegions',id),{enabled:item.enabled===false,updatedBy:currentUser.uid,updatedAt:localTestMode?new Date().toISOString():serverTimestamp()});showRecommendationCategoryManager();};
window.moveRecommendationRegion=async function(id,direction){if(!isAdmin())return;const regions=sortedRecommendationRegions(true),index=regions.findIndex(r=>r.id===id),target=index+direction;if(index<0||target<0||target>=regions.length)return;const first=regions[index],second=regions[target],batch=writeBatch(db);batch.update(doc(db,'recommendationRegions',first.id),{sortOrder:target});batch.update(doc(db,'recommendationRegions',second.id),{sortOrder:index});await batch.commit();if(localTestMode)showRecommendationCategoryManager();};
window.deleteRecommendationRegion=async function(id){if(!isAdmin())return;const item=recommendationRegion(id),used=S.recommendations.filter(r=>r.regionId===id).length;if(!item)return;if(used)return alert(`「${item.name}」仍有 ${used} 則推薦使用，請先改地區或停用。`);if(!confirm(`確定刪除地區「${item.name}」？`))return;await deleteDoc(doc(db,'recommendationRegions',id));if(recommendationRegionFilter===id)recommendationRegionFilter='all';showRecommendationCategoryManager();};
window.addRecommendationCategory=async function(){if(!isAdmin())return;const name=$('recommend-category-name').value.trim(),key=normalizeRecommendationName(name);if(!key)return alert('請輸入類別名稱。');if(S.recommendationCategories.some(c=>normalizeRecommendationName(c.name)===key))return alert('已有相同或過於相近的類別名稱。');const categories=sortedRecommendationCategories(true),stamp=localTestMode?new Date().toISOString():serverTimestamp();await addDoc(collection(db,'recommendationCategories'),{name,normalizedName:key,sortOrder:categories.length,enabled:true,createdBy:currentUser.uid,createdAt:stamp,updatedAt:stamp});showRecommendationCategoryManager();};
window.toggleRecommendationCategory=async function(id){if(!isAdmin())return;const item=recommendationCategory(id);if(!item)return;await updateDoc(doc(db,'recommendationCategories',id),{enabled:item.enabled===false,updatedBy:currentUser.uid,updatedAt:localTestMode?new Date().toISOString():serverTimestamp()});showRecommendationCategoryManager();};
window.moveRecommendationCategory=async function(id,direction){if(!isAdmin())return;const categories=sortedRecommendationCategories(true),index=categories.findIndex(c=>c.id===id),target=index+direction;if(index<0||target<0||target>=categories.length)return;const first=categories[index],second=categories[target],batch=writeBatch(db);batch.update(doc(db,'recommendationCategories',first.id),{sortOrder:target});batch.update(doc(db,'recommendationCategories',second.id),{sortOrder:index});await batch.commit();if(localTestMode)showRecommendationCategoryManager();};
window.deleteRecommendationCategory=async function(id){if(!isAdmin())return;const item=recommendationCategory(id),used=S.recommendations.filter(r=>r.categoryId===id).length;if(!item)return;if(used)return alert(`「${item.name}」仍有 ${used} 則推薦使用，請先改分類或停用。`);if(!confirm(`確定刪除類別「${item.name}」？`))return;await deleteDoc(doc(db,'recommendationCategories',id));showRecommendationCategoryManager();};
